### PR TITLE
Patch to fix issue 2341

### LINKED ISSUE #2341: Failed to get RecentStats("/") while determining the next housekeeping: unable to find data in memory cache
I have cadvisor runned as systemd unit on centos7 server, and on logs every minute i see an error: `cadvisor[103112]: W1120 14:47:56.678182  103112 container.go:422] Failed to get RecentStats("/") while determining the next housekeeping: unable to find data in memory cache`
What is this and how to fix it?

**OS:** CentOS Linux release 7.7.1908 (Core)
**Cadvisor version:** v0.34.0 (24a6a52f)
**Runned with flags:** `--docker=unix:///var/run/docker.sock --listen_ip=192.168.49.177 --port=4194 --disable_root_cgroup_stats=true --docker_only=true --logtostderr=true`
**validate:**
```
cAdvisor version: v0.34.0

OS version: CentOS Linux 7 (Core)

Kernel version: [Supported and recommended]
	Kernel version is 3.10.0-957.27.2.el7.x86_64. Versions >= 2.6 are supported. 3.0+ are recommended.


Cgroup setup: [Supported and recommended]
	Available cgroups: map[blkio:1 cpu:1 cpuacct:1 cpuset:1 devices:1 freezer:1 hugetlb:1 memory:1 net_cls:1 net_prio:1 perf_event:1 pids:1]
	Following cgroups are required: [cpu cpuacct]
	Following other cgroups are recommended: [memory blkio cpuset devices freezer]
	Hierarchical memory accounting enabled. Reported memory usage includes memory used by child containers.
	Cpu cfs bandwidth is enabled.


Cgroup mount setup: [Supported and recommended]
	Cgroups are mounted at /sys/fs/cgroup.
	Cgroup mount directories: blkio cpu cpu,cpuacct cpuacct cpuset devices freezer hugetlb memory net_cls net_cls,net_prio net_prio perf_event pids systemd 
	Any cgroup mount point that is detectible and accessible is supported. /sys/fs/cgroup is recommended as a standard location.
	Cgroup mounts:
	cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_prio,net_cls 0 0
	cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0


Docker version: [Supported and recommended]
	Docker version is 19.03.2. Versions >= 1.0 are supported. 1.2+ are recommended.


Docker driver setup: [Supported and recommended]
	Storage driver is overlay2.


Block device setup: [Supported, but not recommended]
	None of the devices support 'cfq' I/O scheduler. No disk stats can be reported.
	 Disk "dm-0" Scheduler type "none".
	 Disk "dm-14" Scheduler type "none".
	 Disk "sdf" Scheduler type "deadline".
	 Disk "dm-11" Scheduler type "none".
	 Disk "dm-2" Scheduler type "deadline".
	 Disk "sdc" Scheduler type "deadline".
	 Disk "dm-8" Scheduler type "none".
	 Disk "dm-1" Scheduler type "none".
	 Disk "dm-13" Scheduler type "none".
	 Disk "sdd" Scheduler type "deadline".
	 Disk "dm-12" Scheduler type "none".
	 Disk "dm-15" Scheduler type "none".
	 Disk "dm-3" Scheduler type "deadline".
	 Disk "dm-5" Scheduler type "deadline".
	 Disk "dm-6" Scheduler type "deadline".
	 Disk "sdg" Scheduler type "deadline".
	 Disk "sdk" Scheduler type "deadline".
	 Disk "dm-10" Scheduler type "none".
	 Disk "dm-4" Scheduler type "deadline".
	 Disk "dm-7" Scheduler type "none".
	 Disk "sde" Scheduler type "deadline".
	 Disk "sdh" Scheduler type "deadline".
	 Disk "sdi" Scheduler type "deadline".
	 Disk "sdj" Scheduler type "deadline".
	 Disk "dm-9" Scheduler type "none".
	 Disk "sda" Scheduler type "deadline".
	 Disk "sdb" Scheduler type "deadline".


Inotify watches: 
	

Managed containers: 
	/docker/885218b4482590eacd6b833b73ace81ea47bec55d289f938bed9212598a395aa
		Namespace: docker
		Aliases:
			kibana
			885218b4482590eacd6b833b73ace81ea47bec55d289f938bed9212598a395aa
	/docker/8d0e2be90b560d0f010caf54f19beb2bf351cbfc72ad167085978017c2cfd274
		Namespace: docker
		Aliases:
			logger
			8d0e2be90b560d0f010caf54f19beb2bf351cbfc72ad167085978017c2cfd274
	/
	/docker/8c81f9da5fd00038183e70f624784a7f00fa394b8e57db8da049e78ccc7dd9b3
		Namespace: docker
		Aliases:
			grafana
			8c81f9da5fd00038183e70f624784a7f00fa394b8e57db8da049e78ccc7dd9b3
	/docker/21470eaa8aba17420810a41a0c132e353ae9dd8284b1ee308aa8dd61e8618eff
		Namespace: docker
		Aliases:
			kibana_nginx
			21470eaa8aba17420810a41a0c132e353ae9dd8284b1ee308aa8dd61e8618eff
	/docker/7641d657dde2d2cb742e02235e771563a8cbd90323c8a9138e250dba3b7231d0
		Namespace: docker
		Aliases:
			prometheus
			7641d657dde2d2cb742e02235e771563a8cbd90323c8a9138e250dba3b7231d0
	/docker/85d6202f073cd8b3c11b8876e12aff5707874b7bee6a526c3967e46103fcf991
		Namespace: docker
		Aliases:
			elasticsearch
			85d6202f073cd8b3c11b8876e12aff5707874b7bee6a526c3967e46103fcf991
	/docker/876c03fb744659d908f7438cdef53014e8d5cb8b910e71a83e99def44fbd7463
		Namespace: docker
		Aliases:
			registry_ui
			876c03fb744659d908f7438cdef53014e8d5cb8b910e71a83e99def44fbd7463
	/docker/b741731238af219329e4e87a9e8f82f91f46795de1f64d762db085c29a6c6dbc
		Namespace: docker
		Aliases:
			resolver
			b741731238af219329e4e87a9e8f82f91f46795de1f64d762db085c29a6c6dbc
```

### PR DESCRIPTION
**Pull request by geek-bit**
This patch will ignore the warning 
`Failed to get RecentStats("/") while determining the next housekeeping: unable to find data in memory cache`
for root cgroup when `--disable_root_cgroup_stats` flag is set to true.

Closes #2341

### CODE REVIEW

**Comment by bobbypage** [comment]
Please run `gofmt` on the files

```
manager/container.go:489: File is not `gofmt`-ed with `-s` (gofmt)
			if cd.allowErrorLogging() && !(cd.isRoot() && *raw.DisableRootCgroupStats){
make: *** [Makefile:94: lint] Error 1
```

**Comment by pawandeep-uber** [comment]
@bobbypage any ETA on when this PR can be merged?

**Comment by applike-ss** [comment]
I'm also waiting to see this merged

**Comment by michael-strigo** [comment]
This issue is spamming the logs like crazy.

**Comment by iwankgb** [comment]
Duplicate of #3341.

**Pull request closed without merging**
