### PR TITLE
Rename load to load average.

### PR DESCRIPTION
**Pull request by rjnagal**
Load is now LoadAverage. Also added comments about smoothing interval.

### CODE REVIEW

**Comment by rjnagal** [comment]
Missed out the final comment update in the last PR.

**Comment by vishh** [comment]
LGTM

**Comment by vmarmol** [comment]
LGTM

**Comment by vishh** [comment]
Travis is unhappy.

**Comment by rjnagal** [comment]
Updated. Added a TODO to handle load in integration test. The current assert of load being zero is no longer good :)

**Comment by vmarmol** [comment]
LGTM

**Pull request merged**
