### PR TITLE
Fix #2583, update opencontainers/runc

### LINKED ISSUE #2583: memory.numa_stat not found
I was trying build image using dockerfile in deploy/Dockerfile .. i was facing error failed to get container "/" with error: unable to find data in memory cache 

`Failed to update stats for container "/": open /sys/fs/cgroup/memory/memory.numa_stat: no such file or directory`

@iwankgb

### PR DESCRIPTION
**Pull request by katarzyna-z**
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>

Update opencontainers/runc to version which includes https://github.com/opencontainers/runc/pull/2470

@dashpole @vynu Could you verify if this fixes #2583?

@giuseppe if this fixes the issue it'll be good to update opencontainers/runc in your pull request https://github.com/kubernetes/kubernetes/pull/91366

### CODE REVIEW

**Comment by giuseppe** [comment]
> @giuseppe if this fixes the issue it'll be good to update opencontainers/runc in your pull request [kubernetes/kubernetes#91366](https://github.com/kubernetes/kubernetes/pull/91366)

@katarzyna-z thanks for letting me know.  I've updated kubernetes/kubernetes#91366 to use the same opencontainers/runc commit

**Comment by dashpole** [comment]
I'll wait to merge for verification from @vynu that this fixes their issue.

**Comment by iwankgb** [comment]
@katarzyna-z 🙇

**Comment by vynu** [comment]
trying to create and test image based on ..katarzyna-z:kk-fix-memory-numa-stats.. will get back here with results shortly 
thank you @dashpole

**Comment by vynu** [comment]
@dashpole @iwankgb @katarzyna-z .. tested new image .. working good .. thank you guys for the real quick fix

**Pull request merged**
