### PR TITLE
rename dockerOnly flag as its not accurate description anymore

### PR DESCRIPTION
**Pull request by sjpotter**
Should be fairly self explanitory

### CODE REVIEW

**Comment by vishh** [comment]
Should we mark the flag as deprecated before removing it?

**Comment by sjpotter** [comment]
can do that too. is their a normal way to do that?

**Comment by vishh** [comment]
We use golang flags package. So deprecation will have to handled manually. Just post a message saying that the flag will be removed in a subsequent release and switch to using the new flag should do.

**Comment by timstclair** [comment]
See my comment on https://github.com/google/cadvisor/issues/1201#issue-147065503

I think `-runtime_only` is a bit weird, and we should just give the option to control which container handlers are enabled (default should be all). As for deprecating, I'd just update the usage message to be `DEPRECATED: Use -container_handlers instead` (or whatever the new flag is).

**Pull request closed without merging**
