### PR TITLE
Revert "allow ignoreMetrics in new manager"

### PR DESCRIPTION
**Pull request by vishh**
Build is broken after #1159 was merged. Opening this PR to fix CI.

Build failure [logs here](https://storage.cloud.google.com/kubernetes-jenkins/logs/cadvisor-gce-e2e-ci/40).

### CODE REVIEW

**Comment by vishh** [comment]
cc @timstclair

**Comment by timstclair** [comment]
cc @sjenning @ncdc @derekwaynecarr

**Comment by ncdc** [comment]
What CI failed - I'm guessing you have something besides the Jenkins GCE e2e?

**Comment by vishh** [comment]
We run CI on HEAD. I believe the PR was merged before the CI was happy with
the most recent commit.

**Comment by timstclair** [comment]
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/cadvisor-gce-e2e-ci/41/

I'm not sure that this caused the issue, but we're having trouble debugging, so decided to try the rollback.

**Comment by timstclair** [comment]
Oops, updated to external link.

**Comment by vishh** [comment]
@k8s-bot test again

**Comment by ncdc** [comment]
It appears there's an issue with the way that CI is running the integration tests. It's invoking like this:

```
"godep" ["go" "test" "--timeout" "15m0s" "" "github.com/google/cadvisor/integration/tests/..." "--host" "e2e-cadvisor-container-vm-v20160127" "--port" "8080" "--ssh-options" "-i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no"]
```

Notice the empty string argument in between 15m0s and github.com/google/cadvisor/integration/tests/... . Because of that empty string, CI is basically just running `godep go test ... --host ...`.

The reason that CI is failing is because --host is not a valid flag for the new cadvisor_test.go that was added in Seth's PR in the project root.

**Comment by vishh** [comment]
That flag is part of the integration test framework. Why would the PR
affect the test framework?

**Comment by ncdc** [comment]
@vishh it doesn't affect the test framework, per se. What happened is the PR added a new test at the root of the project directory, where one didn't exist before. And because there is no `--host` flag at the root (it only exists in the integration test code), things fail. Can you all fix how Jenkins invokes `godep go test` to get rid of that empty string argument?

**Pull request closed without merging**
