### PR TITLE
Bump github.com/prometheus/client_golang and related

### PR DESCRIPTION
**Pull request by zhsj**
+ github.com/prometheus/client_golang v0.9.1 -> v1.0.0
+ github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4 -> v0.2.0
+ github.com/prometheus/common v0.0.0-20170220103846-49fee292b27b -> v0.4.1

Sync with the version used in k8s.
Other changes in go.mod are caused by `go mod tidy`

### CODE REVIEW

**Comment by dashpole** [comment]
any idea why the grpc version decreased?  It went from v1.26.0 -> v1.24.0

**Comment by zhsj** [comment]
> any idea why the grpc version decreased? It went from v1.26.0 -> v1.24.0

no idea... I try to pin it at v1.26.0 and run `go mod tidy` again, now it looks fine.

**Comment by dashpole** [comment]
Sorry I didn't get back to this.  If you rebase, I can take another look.

**Comment by zhsj** [comment]
> Sorry I didn't get back to this. If you rebase, I can take another look.

Rebased. Since a previously commit did't run `go mod tidy` when introducing `github.com/google/go-cmp/cmp`, this PR now has fixed it too by running `go mod tidy & go mod vendor`.

**Pull request merged**
