### PR TITLE
Cherrypick #1002

### PR DESCRIPTION
**Pull request by timstclair**
Cherrypick #1002 to unblock https://github.com/kubernetes/kubernetes/issues/18044

### CODE REVIEW

**Comment by timstclair** [comment]
@k8s-bot add to whitelist

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
add to whitelist

**Comment by vishh** [comment]
@timstclair: Add yourself to the admin list for triggering builds.

**Comment by vishh** [comment]
Feel free to self-merge once build passes.

**Pull request merged**
