### PR TITLE
Godeps clean up

### PR DESCRIPTION
**Pull request by jimmidyson**
Bumped prometheus client for some performance fixes & cleaned up unnecessary godeps. Nearly works with `godep restore` now - just a dodgy docker vendored package to get rid of.

Prompted by #911.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Jenkins seems to have got confused with the PR commits vs previous ones... the flake is due to that for some reason. @vishh ?

**Comment by jimmidyson** [comment]
@mvdan @vishh Bit of a cleanup of godeps, including moving to new location for google API packages & upgrading prometheus packages.

**Comment by mvdan** [comment]
Jenkins does that for some reason sometimes (picking up the wrong set of commits to merge). We never quite figured out why.

I assume this godeps cleanup is similar to those done in heapster? At a quick glance LGTM.

**Comment by mvdan** [comment]
Thanks for the cleanup @jimmidyson!

**Comment by jimmidyson** [comment]
@mvdan Yeah this is done exactly the same as I did for Heapster, with the exception that I had to migrate packages for bigquery API.

Merging...

**Pull request merged**
