### PR TITLE
Release v0.20.2

### PR DESCRIPTION
**Pull request by vishh**
cc @timstclair @pwittrock

### CODE REVIEW

**Comment by vishh** [comment]
Self merging to create a tag asap

**Comment by pwittrock** [comment]
LGTM

**Comment by timstclair** [comment]
/cc @jimmidyson 

Thansk Vish!

**Comment by jimmidyson** [comment]
This doesn't include the libcontainer update I wanted to get in to next release so will have to cut another old next week once libcontainer is tagged.

**Pull request merged**
