### PR TITLE
Remove RecentStats() from all storage drivers except memory.

### PR DESCRIPTION
**Pull request by rjnagal**
We should probably make memory as a cache type rather than storage.
RecentStats() can then be removed from the storage interface.
Will try it out as a separate PR.

### CODE REVIEW

**Comment by rjnagal** [comment]
fyi @mnuessler

**Comment by vmarmol** [comment]
We started treating memory as a cache and not a storage driver so it should be easier to make the change :)

**Comment by vmarmol** [comment]
LGTM, nice! removes lots of code.

**Comment by rjnagal** [comment]
yeah, cache seems pretty straightforward. Might get to it today :)

**Pull request merged**
