### PR TITLE
vendor: bump runc to 1.1.9

### PR DESCRIPTION
**Pull request by haircommander**
to fix an issue with cgroupv2 memory accounting not being accurate

### CODE REVIEW

**Comment by kolyshkin** [comment]
@haircommander I think you forgot to run `go mod tidy`.

**Comment by haircommander** [comment]
hm, running it doesn't change the files there

**Comment by bobbypage** [comment]
@haircommander can you please rebase to include https://github.com/google/cadvisor/pull/3380? That should fix the issues with the CI. Thank you!

**Comment by haircommander** [comment]
yeah I've rebased and definitely have the fixes. Any hints here?

**Comment by bobbypage** [comment]
Can you run `make tidy`?

**Comment by haircommander** [comment]
ah hah! that was it, thank you

**Comment by bobbypage** [comment]
Great! Can you please also remove the change to the `.gitignore`? I don't think that is needed.

**Comment by haircommander** [comment]
sure, though I added it because the vendor directory is generated when we run `go mod vendor` but not checked into the repo...

**Comment by bobbypage** [comment]
> sure, though I added it because the vendor directory is generated when we run `go mod vendor` but not checked into the repo...

gotcha, we don't vendor in cadvisor, so there shouldn't be a vendor directory and running `go mod vendor` shouldn't be necessary.

**Pull request merged**
