### PR TITLE
replace pannic with fmt.Errorf in the error handling of elasticsearch storage 

### PR DESCRIPTION
**Pull request by wangzhezhe**

### CODE REVIEW

**Comment by vishh** [comment]
Thanks for the cleanup.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
Travis failure is unrelated to this failure. Once #1031 is merged, this PR should hopefully pass all tests.

**Comment by pwittrock** [comment]
@k8s-bot test this please

**Comment by pwittrock** [comment]
@k8s-bot test this please

flaky failure about not having an authenticated account

**Comment by vishh** [comment]
ok to test

**Comment by wangzhezhe** [comment]
Thanks for your concern , but why some checks were still not successful ?  I hope that I could contribute more effective codes in future.

**Comment by pwittrock** [comment]
@wangzhezhe The default check appears to be failing because it is in a bad state.  The "Jenkins GCE e2e" check is meant to replace it, so you can ignore default for now.  I have disable the default check for future PRs.

**Comment by wangzhezhe** [comment]
@pwittrock Thank you for the reply！

**Pull request merged**
