### PR TITLE
Added fix for Kubernetes btrfs issue #47046

### PR DESCRIPTION
**Pull request by flavio**
Sorry for the short description, all the details can be found here: https://github.com/kubernetes/kubernetes/issues/47046

### CODE REVIEW

**Comment by flavio** [comment]
@googlebot  I signed it!

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by dashpole** [comment]
Thanks for this.  Ill try and get to this in the next week, but I am pretty busy atm.

**Comment by dashpole** [comment]
Have you vendored (or just copied) these changes into kubernetes to verify that they work?
Code changes look great!

**Comment by flavio** [comment]
Yes I did: all the error messages disappeared and everything seems to be working fine.

**Comment by dashpole** [comment]
can you rebase?  Then I will merge this.

**Comment by flavio** [comment]
Rebase done.

**Pull request merged**
