### PR TITLE
Remove sched debug based load implementation.

### PR DESCRIPTION
**Pull request by rjnagal**

### CODE REVIEW

**Comment by rjnagal** [comment]
@kateknister

**Comment by rjnagal** [comment]
@kateknister The events integration test is failing:
--- FAIL: TestStreamingEventInformationIsReturned (79.28s)\n
\tevent_test.go:38: Started event streaming with error json: cannot unmarshal array into Go value of type v1.Event\n
\tassertions.go:156: \r                        \r\tLocation:\tevent_test.go:39\n\t\t\r\tError:\t\tNo error is expected but got json: cannot unmarshal array into Go value of type v1.Event\n\t\t\r\n
\tframework.go:294: Ran \"sudo\" [docker run -m=4M --name test-basic-docker-container-3062 bernardo/stress --vm 4 --vm-keep -q -m 1000 --timeout 10] in \"10.240.129.120\" and received error: \"exit status 159\". Stdout: \"\", Stderr: INFO: Zone for cadvisor-ubuntu-precise detected as us-central1-f.\n\t\tINFO: Running command line: ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no -i /var/lib/jenkins/.ssh/google_compute_engine -A -p 22 jenkins@146.148.64.95 -- sudo docker run -m=4M --name test-basic-docker-container-3062 bernardo/stress --vm 4 --vm-keep -q -m 1000 --timeout 10\n
\t\tWarning: Permanently added '146.148.64.95' (ECDSA) to the list of known hosts.\r\n
\t\tWARNING: Your kernel does not support swap limit capabilities. Limitation discarded.\n
stress: ../nptl/sysdeps/unix/sysv/linux/x86_64/
../fork.c:141: __libc_fork: Assertion `({ __typeof (self->tid) __value; if (sizeof (__value) == 1) asm volatile (\"movb %%fs:%P2,%b0\" : \"=q\" (__value) : \"0\" (0), \"i\" (__builtin_offsetof (struct pthread, tid))); else if (sizeof (__value) == 4) asm volatile (\"movl %%fs:%P1,%0\" : \"=r\" (__value) : \"i\" (__builtin_offsetof (struct pthread, tid))); else { if (sizeof (__value) != 8) abort (); asm volatile (\"movq %%fs:%P1,%q0\" : \"=r\" (__value) : \"i\" (__builtin_offsetof (struct pthread, tid))); } __value; }) != ppid' failed.\n\t\t

stress: ../nptl/sysdeps/unix/sysv/linux/x86_64/
../fork.c:141: __libc_fork: Assertion `({ __typeof (self->tid) __value; if (sizeof (__value) == 1) asm volatile (\"movb %%fs:%P2,%b0\" : \"=q\" (__value) : \"0\" (0), \"i\" (__builtin_offsetof (struct pthread, tid))); else if (sizeof (__value) == 4) asm volatile (\"movl %%fs:%P1,%0\" : \"=r\" (__value) : \"i\" (__builtin_offsetof (struct pthread, tid))); else { if (sizeof (__value) != 8) abort (); asm volatile (\"movq %%fs:%P1,%q0\" : \"=r\" (__value) : \"i\" (__builtin_offsetof (struct pthread, tid))); } __value; }) != ppid' failed.\n\t\t

stress: ../nptl/sysdeps/unix/sysv/linux/x86_64/
../fork.c:141: __libc_fork: Assertion `({ __typeof (self->tid) __value; if (sizeof (__value) == 1) asm volatile (\"movb %%fs:%P2,%b0\" : \"=q\" (__value) : \"0\" (0), \"i\" (__builtin_offsetof (struct pthread, tid))); else if (sizeof (__value) == 4) asm volatile (\"movl %%fs:%P1,%0\" : \"=r\" (__value) : \"i\" (__builtin_offsetof (struct pthread, tid))); else { if (sizeof (__value) != 8) abort (); asm volatile (\"movq %%fs:%P1,%q0\" : \"=r\" (__value) : \"i\" (__builtin_offsetof (struct pthread, tid))); } __value; }) != ppid' failed.\n\t\tstress: FAIL: [1] (416) <-- worker 5 got signal 9\n\t\tstress: 
FAIL: [1] (416) <-- worker 6 got signal 9\n\t\tstress: FAIL: [1] (416) <-- worker 7 got signal 9\n\t\tstress: FAIL: [1] (416) <-- worker 8 got signal 9\n\t\tstress: FAIL: [1] (416) <-- worker 9 got signal 9\n\t\tstress: FAIL: [1] (416) <-- worker 10 got signal 9\n\t\tstress: FAIL: [1] (416) <-- worker 11 got signal 9\n\t\t

**Comment by vmarmol** [comment]
Spoke to @kateknister, I think we have a fix on the way :)

**Comment by rjnagal** [comment]
@cadvisorJenkinsBot test this please

**Comment by vmarmol** [comment]
LGTM, waiting on green.

**Comment by vmarmol** [comment]
Jenkins passed: http://104.154.52.74/job/cadvisor-e2e/779/console

**Pull request merged**
