### PR TITLE
Support for mips

### PR DESCRIPTION
**Pull request by huchengze**
For support for mips.

https://github.com/kubernetes/kubernetes/issues/86749

### CODE REVIEW

**Comment by huchengze** [comment]
@googlebot I signed it!

**Comment by dashpole** [comment]
You will need to rebase on top of #2370 to fix the test.

**Comment by dashpole** [comment]
```
I0107 02:06:10.849] >> checking go formatting
I0107 02:06:11.402] The following files are not properly formatted:
I0107 02:06:11.403] fs/fs.go
```

**Pull request merged**
