### PR TITLE
Update Dockerfile and dependencies

### PR DESCRIPTION
**Pull request by timstclair**
- Update base image to alpine:3.4
- Fix zfs-utils reference (moved to zfs in main)
- Update glibc version to 2.23-r3

Fixes https://github.com/google/cadvisor/issues/1326

### CODE REVIEW

**Comment by vishh** [comment]
LGTM. I wish we can test this on RHEL or CentOS once before merging.

Ping @derekwaynecarr

**Comment by timstclair** [comment]
I spun up a RHEL7 instance on GCE, and I'm trying to run the integration tests against this image, but hitting this error:
```
F0804 18:48:48.415384       1 cadvisor.go:151] Failed to start container manager: inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory
```
The directory name is slightly different:
```
[stclair@cadvisor-rhel cadvisor]$ ls /sys/fs/cgroup
blkio  cpu  cpuacct  cpu,cpuacct  cpuset  devices  freezer  hugetlb  memory  net_cls  perf_event  systemd
```
I'm running with:
```
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  --privileged=true \
  google/cadvisor:test
```

@derekwaynecarr @jimmidyson any suggestions?

**Comment by derekwaynecarr** [comment]
My understanding is that kernel provides no guarantee on ordering of the
name of combined cgroup.  There should be symlinks for each one.
Libcontainer has some code to handle this I believe.

**Comment by jimmidyson** [comment]
The mount point shouldn't be hard coded but read from the mount table. Can't see anywhere this is hard coded so bit confused how directory is failing. Not at a computer right now to take a look though, sorry.

**Comment by timstclair** [comment]
Mount `/proc/mounts` is correct, as are the symlinks. Interestingly, if I omit `--volume=/sys:/sys:ro` that error goes away, but the tests fail with a different error:
```
--- FAIL: TestDockerContainerCpuStats (5.82s)
	Location:	docker_test.go:63
	Error:		No error is expected but got request "http://localhost:8080/api/v1.3/docker/578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249" failed with error: "failed to get Docker container \"578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249\" with error: unable to find Docker container \"578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249\""
	Messages:	Timed out waiting for container "578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249" to be available in cAdvisor: request "http://localhost:8080/api/v1.3/docker/578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249" failed with error: "failed to get Docker container \"578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249\" with error: unable to find Docker container \"578645cef7dad17177ada1bb7041320e00b4895bec4de22a618d27177ad70249\""
```

**Comment by vishh** [comment]
The /sys/ mount is necessary. Libcontainer had a few fixes around cgroups
mounts discovery. When was the last time we updated libcontainer deps?

**Comment by timstclair** [comment]
16 days ago: https://github.com/google/cadvisor/pull/1387

**Comment by vishh** [comment]
@timstclair I tried `google/cadvisor:canary` which is essentially a nightly build and cadvisor fails on RHEL. So the failure is itself not related to this PR.

**Comment by vishh** [comment]
It looks like docker on RHEL is incorrectly mounting cgroups. `cpu,cpuacct` getting mounted inside the container as `cpuacct,cpu`. A libcontainer bug. 

<details>
$ sudo docker run --rm -it  --volume=/:/rootfs:ro   --volume=/var/run:/var/run:rw   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro --privileged=true busybox mount
rootfs on / type rootfs (rw)
/dev/mapper/docker-8:1-50821573-09336c024e0c765d042901fd0de3dc4383b8c064c3a3c7f947683379d9841ce7 on / type xfs (rw,seclabel,relatime,nouuid,attr2,inode64,logbsize=64k,sunit=128,swidth=128,noquota)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,seclabel,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuacct,cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
sysfs on /sys type sysfs (ro,seclabel,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,seclabel,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)

</details>

**Comment by timstclair** [comment]
Thanks for looking into that. Should we move ahead with this PR then?

**Comment by rmmh** [comment]
.

**Comment by vishh** [comment]
Yup. I'm merging this for now!

**Pull request merged**
