### PR TITLE
add nerdctl to ignoredDevices

### LINKED ISSUE #3266: add ignored network Devices
We should add `nerdctl` prefix to [ignoredDevices](https://github.com/google/cadvisor/blob/487e64ac1381fe7f959c7e52f086fa58149ea498/utils/sysinfo/sysinfo.go#L107) since its prefix name is `nerdctlxxx`.

### PR DESCRIPTION
**Pull request by Rouzip**
Fix #3266

### CODE REVIEW

**Review by iwankgb — APPROVED** [review]

**Comment by iwankgb** [comment]
@dims I think it can be merged - such interfaces are indeed created and should be probably ignored.

**Review by dims — APPROVED** [review]
/approve
/lgtm

**Comment by dims** [comment]
/hold

hmmm

**Comment by dims** [comment]
@Rouzip the strings are different, by design? or typo?

image

**Comment by Rouzip** [comment]
> @Rouzip the strings are different, by design? or typo?
> 
> image

Sorry for the late reply, I used “nerdctl0” in the unit test, which is different from the code above. This is because nerdctl will create a virtual bridge like “nerdctlxxx”, similar to docker.
telegram-cloud-document-5-6100215378485446526

**Comment by JOJUNGCHEOL** [comment]
Rouzip:add-nerdctl

**Comment by JOJUNGCHEOL** [comment]
감사드립니다,☺️

**Comment by dims** [comment]
thanks @Rouzip !

**Pull request merged**
