### PR TITLE
Fix v2 stats conversion NPD & add test

### PR DESCRIPTION
**Pull request by timstclair**
Fix for https://github.com/google/cadvisor/issues/1060

### CODE REVIEW

**Comment by timstclair** [comment]
@k8s-bot test this

**Comment by jimmidyson** [comment]
LGTM thanks!

**Comment by timstclair** [comment]
Thanks. Is it possible to cherrypick into a tagged release, or do we need to do another minor release?

**Comment by jimmidyson** [comment]
We have a few different fixes now we need in Kubernetes that should be in next release, although I'm waiting on runc tag before submitting update to Kubernetes (sadly runc tag is waiting on a bug fix too...). I don't mind if we keep doing small cadvisor releases at all but we need to make sure we don't have overlapping cadvisor updates to Kubernetes.

**Comment by timstclair** [comment]
Ok. I realized this is not actually blocking me at the moment, so I'll just wait for the next cAdvisor update to grab all the fixes.

**Comment by vishh** [comment]
Thanks @timstclair. Missed this while rebasing.

**Pull request merged**
