### PR TITLE
Add cache id for cache info.

### PR DESCRIPTION
**Pull request by hustcat**
Add cache id for cache info.

### CODE REVIEW

**Comment by hustcat** [comment]
@dashpole  e2e test seems some problem?

**Comment by hustcat** [comment]
Can anyone review this?

**Comment by hustcat** [comment]
@dashpole Can you review this PR?

**Comment by Creatone** [comment]
@hustcat Only small nit. Add `Id` field to `cacheInfo` inside `TestGetCacheInfo()` (**utils/sysinfo/sysinfo_test.go:1317**)

**Review by Creatone — CHANGES_REQUESTED** [review]
@hustcat Only small nit. Add `Id` field to `cacheInfo` inside `TestGetCacheInfo()` (**utils/sysinfo/sysinfo_test.go:1317**)

**Review by Creatone — APPROVED** [review]
LGTM

**Review by Creatone — APPROVED** [review]

**Pull request merged**
