### PR TITLE
go.mod: github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/kubernetes/kubernetes/pull/104733

Uses an updated version of Microsoft/go-ansiterm, which fixes an overflow
on arm;

full diff: https://github.com/moby/term/compare/df9cb8a40635...3f7ff695adc6

### CODE REVIEW

**Comment by bobbypage** [comment]
```
W1220 19:41:10.608] level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: github.com/google/cadvisor@v0.0.0 requires\n\tgithub.com/moby/term@v0.0.0-20210619224110-3f7ff695adc6: missing go.sum entry; to add it:\n\tgo mod download github.com/moby/term\ngo: github.com/google/cadvisor@v0.0.0 requires\n\tgithub.com/moby/term@v0.0.0-20210619224110-3f7ff695adc6: missing go.sum entry; to add it:\n\tgo mod download github.com/moby/term\n"
```

Appears to be go.sum entry missing based on Prow job above?

**Comment by thaJeztah** [comment]
Oh! I see there's a sub modules in cmd/; I wasn't aware of that; that's probably the one that needs updating as well

**Comment by thaJeztah** [comment]
updated 🤞, but looks like github actions need to be approved again to run 🤗

**Comment by thaJeztah** [comment]
@dims @aojea @bobbypage is one of you able to give CI a kick to make it run?

**Review by bobbypage — APPROVED** [review]

**Pull request merged**
