### PR TITLE
Update libcontainer deps

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by timstclair** [comment]
Is this different from https://github.com/google/cadvisor/pull/1370?

**Comment by vishh** [comment]
Closing #1370

**Comment by timstclair** [comment]
My same comment applies here: should we update to an official tagged release rather than an untagged commit?

**Comment by vishh** [comment]
I'm not sure when runc will post a tag. Meanwhile, head has some build fixes and will also help with unifying dependencies across cadvisor and kube.

**Comment by timstclair** [comment]
Ok, LGTM.

**Pull request merged**
