### PR TITLE
Fix incorrect CPU topology on single NUMA and multi socket platform.

### LINKED ISSUE #2798: Incorrect CPU topology on Single NUMA and Multi socket system leads to performance degradation for POD
*Issue and Impact seen:*

Due to incorrect CPU topology generated by cadvisor (version 0.37), CNF Pod is allocated CPU 1 which is a hyperthread sibling of CPU 0 (CPU 0 hosts most of the OS and other components). This leads performance degradation of the Pod.
In earlier versions (k8s 1.18.9, cadvisor 0.35.0) , CPU allocation happened from CPU 2-14 , whereas in k8s version 1.19.3 , cadvisor version 0.37.0 , CPU allocation happens from CPU 1-13.

*Issue detected version:*

**k8s version 1.19.3 , cadvisor version 0.37.0**

*Version where it works well:*

**k8s version 1.18.9, cadvisor version 0.35.0**

*Analysis done so far:*

1) We see this issue on **Singel NUMA , Multi Socket System**
2) On  version 0.35.0 , topology generated by cadvisor and fed to kubelet looks like below.
    Here there is a clear mapping of node/socket to cores/threads.

        "topology": [
          {
            "node_id": 0,
            "memory": 50628362240,
            "hugepages": [
              {
                "page_size": 1048576,
                "num_pages": 8
              }
            ],
            "cores": [
              {
                "core_id": 0,
                "thread_ids": [
                  0,
                  1
                ],
                "caches": [
                  {
                    "size": 4194304,
                    "type": "Unified",
                    "level": 2
                  }
                ]
              }
            ],
            "caches": [
              {
                "size": 16777216,
                "type": "Unified",
                "level": 3
              }
            ]
          },
          {
            "node_id": 1,
            "memory": 0,
            "hugepages": null,
            "cores": [
              {
                "core_id": 0,
                "thread_ids": [
                  2,
                  3
                ],
                "caches": [
                  {
                    "size": 4194304,
                    "type": "Unified",
                    "level": 2
                  }
                ]
              }
            ],
            "caches": [
              {
                "size": 16777216,
                "type": "Unified",
                "level": 3
              }
            ]
          },
        ... 
        ...
        ]

2) On  version 0.37.0 , topology generated by cadvisor and fed to kubelet looks like below.
    Below there seems to be a mix up of socket and numa nodes.

       "topology": [
          {
            "node_id": 0,
            "memory": 50628362240,
            "hugepages": [
              {
                "page_size": 1048576,
                "num_pages": 8
              }
            ],
            "cores": [
              {
                "core_id": 0,
                "thread_ids": [
                  0,
                  1,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  2,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26,
                  27,
                  28,
                  29,
                  3,
                  30,
                  31,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9
                ],
                "caches": null,
                "socket_id": 4
              }
            ],
            "caches": null
          }
        ]

4) We suspect that following commit has introduced the bug.

        commit c5a9232a94846cdd9f2a80b3a969a7717e880e10
        Author: Katarzyna Kujawa <katarzyna.kujawa@intel.com>
        Date: Wed Mar 4 11:33:46 2020 +0100

### PR DESCRIPTION
**Pull request by Creatone**
Fixes #2798

Signed-off-by: Paweł Szulik <pawel.szulik@intel.com>

### CODE REVIEW

**Comment by kashifest** [comment]
It seems physical package id is missing, 
`[sysinfo.go:406] Cannot read physical package id for /fakeSysfs/devices/system/node/node0/cpu1, physical_package_id file does not exist, err: file does not exist
`
are we calling GetCPUPhysicalPackageID at the correct location ?

**Comment by Creatone** [comment]
> It seems physical package id is missing,
> `[sysinfo.go:406] Cannot read physical package id for /fakeSysfs/devices/system/node/node0/cpu1, physical_package_id file does not exist, err: file does not exist `
> are we calling GetCPUPhysicalPackageID at the correct location ?

This PR was draft at this time. Now it's ready for review.

**Review by kashifest — APPROVED** [review]

**Review by iwankgb — APPROVED** [review]
LGTM

**Review by iwankgb — CHANGES_REQUESTED** [review]
I have to un-LGTM it: it may cause yet another set of issues with kubelet (see comments in the linked issue).

**Comment by Creatone** [comment]
> I have to un-LGTM it: it may cause yet another set of issues with kubelet (see comments in the linked issue).

Unfortunately, issues are already there. This PR fixes only one issue, the wrong threads to CPU matching.

**Comment by iwankgb** [comment]
I know but CPU manager must not be affected - keep in mind that it is enabled for all guaranteed pods by default.

**Comment by Insullone** [comment]
@Creatone We tested the fix and it can detect cpu topologies correctly. By the way, could you backport the fix to 0.38.x as well?

**Review by iwankgb — APPROVED** [review]

**Comment by Insullone** [comment]
Just clarify: when I said "We tested the fix and it can detect cpu topologies correctly", I meant it fixed the specific issue "wrong threads to CPU matching".

**Review by bobbypage — COMMENTED** [review]
Thanks @Creatone for the fix. Can you please explain what the issue was / how this fixes it, I'm not super clear? Is the issue due to missing check of `core.SocketID == physicalPackageID`?

**Comment by Creatone** [comment]
@bobbypage Imagine you have a platform with one NUMA node and 4 sockets with one CPU in. In this case, every CPU has core_id = 0, so cAdvisor was putting them in the same core in topology.
Ex.
```
"topology": [
   {
     "node_id": 0,
     "memory": 50628362240,
     "hugepages": [
       {
         "page_size": 1048576,
         "num_pages": 8
       }
     ],
     "cores": [
       {
         "core_id": 0,
         "thread_ids": [
           0,
           1,
           2,
           3,
         ],
         "caches": null,
         "socket_id": 3
       }
     ],
     "caches": null
   }
 ]
 ```
 And this is wrong. We need to differentiate these CPUs. It's needed to consist of `psychical_package_id` in our topology discovery. This parameter describes on which socket is CPU.
 This is the output that we need:
 ```
 "topology": [
   {
     "node_id": 0,
     "memory": 50628362240,
     "hugepages": [
       {
         "page_size": 1048576,
         "num_pages": 8
       }
     ],
     "cores": [
       {
         "core_id": 0,
         "thread_ids": [
           0
         ],
         "caches": null,
         "socket_id": 0
       },
       {
         "core_id": 1,
         "thread_ids": [
           1
         ],
         "caches": null,
         "socket_id": 1
       },
       {
         "core_id": 2,
         "thread_ids": [
           2
         ],
         "caches": null,
         "socket_id": 2
       },
       {
         "core_id": 3,
         "thread_ids": [
           3
         ],
         "caches": null,
         "socket_id": 3
       },
     ],
     "caches": null
   }
 ]
 ```

**Comment by hanamantagoudvk** [comment]
@Creatone @bobbypage : Is the review ok ? If review is done, it needs to be merged.

**Comment by bobbypage** [comment]
got it, thanks @Creatone for the fix. LGTM.

**Pull request merged**
