### PR TITLE
Make all links relative.

### LINKED ISSUE #513: Allow root url to be defined aka be nicer to reverse proxies
Right now cadvisor assumes it's in charge of `/` and uses absolute urls for everything.  This makes it difficult to put a reverse proxy infront and serve cadvisor from differnt urls.  For example, I'd like have Apache httpd listen on port 80, use ldap for ACLs, and then proxy `:80/cadvisor/`to cadvisor running on a port that's only on localhost.  Either (A) avoidance of absolute urls (B) allow some sort of 'CADVISOR_HTTP_ROOT'  (default: `/`) shoud work.

### LINKED ISSUE #566: Add Filtering list of subcontainers
It would be nice to have the subcontainers in a sorted order if possible by subcontainer name on the UI, as well as a search bar to quickly filter subcontainers by name.

### LINKED ISSUE #596: Allow subfolder hosting, stop using absolute paths
There is a cool container called frontdoor:
https://registry.hub.docker.com/u/clue/frontroute/

Cadvisor doesn't work good with it. The css stuff is lost due to aabsolute paths in the cadvisor html code.

### LINKED ISSUE #667: cAdvisor + nginx in different then "/" context
Hello,

I'm trying to run cAdvisor docker image with nginx proxy. The problem is that I need to set up a proxy from different then root context - my goal is to have cAdvisor running behind e.g. `http://localhost/cadvisor/` Here is my exemplary nginx config:

    server {
      listen 82;
      server_name ${HOSTNAME};
  
      set $cadvisor cadvisor.docker;
  
      location ~ ^/cadvisor/(.*)$ {
        rewrite ^/cadvisor/(.*) /$1 break;
        proxy_pass              http://$cadvisor:8080;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout   150;
        proxy_send_timeout      100;
        proxy_read_timeout      100;
        proxy_buffers           16 64k;
        proxy_busy_buffers_size 64k;
        client_max_body_size    256k;
        client_body_buffer_size 128k;
      }
    }

The problem is that application assumes that the web context is set to "/", that's why I get redirected to http://localhost:82/containers/ after accessing http://localhost:82/cadvisor/

Is it possible to define application base context path to make cadvisor running behind custom nginx location? Any help will be appreciate

### PR DESCRIPTION
**Pull request by vmarmol**
This will allow cAdvisor to be reverse proxied, and fixes a long-standing feature request :)

Fixes #513
Fixes #566
Fixes #596
Fixes #667

### CODE REVIEW

**Comment by rjnagal** [comment]
LGTM

**Comment by schmichri** [comment]
+1

**Comment by AnthonyWC** [comment]
Re: https://github.com/google/cadvisor/issues/667

I tested (via https://x.x.x.x/cadvisor/):

```
    location /cadvisor/ {
      proxy_pass         http://prometheus_cadvisor_1:8080/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Forwarded-For $remote_addr;
    }
```

Results in 404 but this work

```
    location / {
      proxy_pass         http://prometheus_cadvisor_1:8080/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Forwarded-For $remote_addr;
    }
```

So issue still exists as they reverted the change earlier and never fix it.

I can manually specify the url path, like this:

```
    location / {
      proxy_pass         http://prometheus_cadvisor_1:8080/containers/;
      proxy_set_header   Host $host;
      proxy_set_header   X-Forwarded-For $remote_addr;
    }
```

It doesn't display properly but doesn't show 404 error, and any non /containers/ links will break.

**Pull request merged**
