### PR TITLE
re-order the import package

### PR DESCRIPTION
**Pull request by carmark**
Make sure the import package in each file as the follow order:
* `golang` self package
* `cadvisor` package
* third-party package

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thanks for the PR. Did you do this manually or via a tool like `goimports`? If via a tool then can we also get the check added to the build scripts to verify subsequent PRs don't mess up ordering?

**Comment by carmark** [comment]
@jimmidyson 

I read the code, and modify the import packages manually at the same time.  The tool `goimports` seems not working for this change.

**Comment by jimmidyson** [comment]
Why do you feel strongly about this package order? What different order does `goimports` produce? My issue with manually doing this is keeping it ordered going forward. Need tooling to support.

**Comment by carmark** [comment]
This order make the packages imported very clear, the tool `goimports` will only separate the golang packages and other packages into two parts.  However, the order of this patch will have another parts.

It is truly that there is no any tool to support this, and I do not very strongly feel this patch is very necessary, but [kubernetes](https://github.com/kubernetes/kubernetes) uses this kind of order.

**Comment by jimmidyson** [comment]
OK that makes sense.

Going to have to keep a close eye on import order in future.

Thanks!

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
Merging as the integration testing environment is broken, but this change only affects import order & unit tests pass.

**Comment by jimmidyson** [comment]
Thanks @carmark.

**Comment by carmark** [comment]
Thanks @jimmidyson.  I will also try to keep a close eye on the new import packages.

**Pull request merged**
