### PR TITLE
Include log usage for aufs driver.

### PR DESCRIPTION
**Pull request by vishh**
Signed-off-by: Vishnu Kannan <vishnuk@google.com>

cc @yujuhong

### CODE REVIEW

**Comment by vishh** [comment]
@jimmidyson: PTAL.

**Comment by jimmidyson** [comment]
After recent discussion, happy with this approach.

One thing: could you enable the storage auditing regardless of the storage driver & only add the aufs dir if aufs is being used? Right now this only works for aufs storage driver but we could still track log usage for any storage drivers.

**Comment by vishh** [comment]
@jimmidyson: Makes sense. Updated.

**Comment by jimmidyson** [comment]
LGTM

**Comment by vishh** [comment]
I appreciate the thorough review @jimmidyson!

**Comment by jimmidyson** [comment]
No worries at all!

**Pull request merged**
