### PR TITLE
add support for swap in machine/info

### PR DESCRIPTION
**Pull request by pacoxu**
Fixes https://github.com/google/cadvisor/issues/2961

### CODE REVIEW

**Comment by pacoxu** [comment]
any update?

**Comment by bobbypage** [comment]
Thanks for the PR!

/cc @mmiranda96

**Review by ehashman — COMMENTED** [review]
/lgtm
:+1:

**Comment by pacoxu** [comment]
/cc @bobbypage @giuseppe 
ack, do you have time to review this one?

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by bobbypage** [comment]
close, re-open to kick CI

**Comment by pacoxu** [comment]
> close, re-open to kick CI

All checks have passed. ✅

**Comment by bobbypage** [comment]
lgtm, thank you!

**Pull request merged**
