### PR TITLE
Simple fix to format string

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by vmarmol** [comment]
Thanks @justinsb! LGTM

**Comment by vmarmol** [comment]
ok to test

**Comment by justinsb** [comment]
Oh, weird.... the failure looks real, though unrelated:

```
$ go vet github.com/google/cadvisor/...
http/handlers.go:75: result of fmt.Errorf call not used
exit status 1
```

I'll submit another trivial PR for that one.  Then this PR should pass tests.

**Comment by vmarmol** [comment]
ok to test

**Pull request merged**
