### PR TITLE
Backporting  #2750, #2755 and #2770 to 0.38

### PR DESCRIPTION
**Pull request by iwankgb**
Backports fixes to:
* #2750 
* #2755 
* #2770 

Brought to my attention in #2814.

### CODE REVIEW

**Comment by iwankgb** [comment]
@pkagrawal I need your consent to backport a bugfix to 0.38 branch.

**Comment by pkagrawal** [comment]
LGTM

**Comment by iwankgb** [comment]
@pkagrawal I'm afraid that the bot is expecting very precise message, one of the bot's comments above.

**Comment by pkagrawal** [comment]
@googlebot I consent.

**Comment by pkagrawal** [comment]
@googlebot I consent.

**Comment by iwankgb** [comment]
@bobbypage can you merge and release a new version, please?

**Pull request closed without merging**
