### PR TITLE
Added flag to manually set machine info refresh rate

### PR DESCRIPTION
**Pull request by ivenk**
Solves #2141. 

Hi,
I found ticket #2141 and wanted to create a more generic solution than provided in #2172. 

Currently the machine info displayed on the web page gets updated every 1000ms. I implemented a new flag which replaces the old hard coded value. The flag has the default value 1000 in order to not change the default behavior. However the flag can be used to set a customized refresh rate (in ms). The flag is named machine_info_refresh_rate. 

On my system it passes all test.

### CODE REVIEW

**Comment by ivenk** [comment]
I signed it!

**Comment by dashpole** [comment]
are we using this flag for anything in cAdvisor itself?  Or just as a way to pass this value to the UI?

**Comment by ivenk** [comment]
@dashpole just to get the value to the ui.

**Comment by ivenk** [comment]
I'm going to look into the test results in the next few days.

**Comment by ivenk** [comment]
Currently I don't have the time to fix this.

**Pull request closed without merging**
