### PR TITLE
Clean up cAdvisor Godeps

### PR DESCRIPTION
**Pull request by timstclair**
Workflow:
```
$ go get -u github.com/tools/godep
$ godep restore
$ rm -rf Godeps
$ godep save ./...
```

This deletes orphaned packages such as
github.com/fsouza/go-dockerclient, and cleans up the workspace to match
the latest godeps rules (e.g. don't vendor vendor directories).

/cc @vishh

### CODE REVIEW

**Comment by Random-Liu** [comment]
@timstclair Test failed. :)

**Comment by timstclair** [comment]
@k8s-bot test this

**Comment by timstclair** [comment]
Looks like a flake, but that's the second time I've seen it: https://github.com/google/cadvisor/issues/1257

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
