### PR TITLE
Add support for xfs.

### PR DESCRIPTION
**Pull request by rjnagal**

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
Tests failing:

```
+ godep go test -v -race -test.short github.com/google/cadvisor/...
# github.com/google/cadvisor/fs
fs/fs.go:82: const initializer map[string]bool literal is not a constant
fs/fs.go:84: mount.FsType undefined (type *mount.MountInfo has no field or method FsType)
# github.com/google/cadvisor/fs
fs/fs.go:82: const initializer map[string]bool literal is not a constant
fs/fs.go:84: mount.FsType undefined (type *mount.MountInfo has no field or method FsType)
godep: go exit status 2
```

**Comment by rjnagal** [comment]
fixed.

**Pull request merged**
