### PR TITLE
Remove PSP from kustomize deploy

### PR DESCRIPTION
**Pull request by bobbypage**
Removing PSP and related config since it is deprecated in 1.25.0.

Users can add their own config if needed (the example deploy is just simple namespace, daemonset, and service account).

Signed-off-by: David Porter <david@porter.me>

### CODE REVIEW

**Comment by bobbypage** [comment]
Test:


```
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.25.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋


$ kubectl get nodes -o wide
NAME                 STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION           CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane   47s   v1.25.2   192.168.8.2   <none>        Ubuntu 22.04.1 LTS   5.18.16-1rodete4-amd64   containerd://1.6.8

$ kubectl kustomize deploy/kubernetes/base | kubectl apply -f -
namespace/cadvisor created
serviceaccount/cadvisor created
daemonset.apps/cadvisor created

$ k get pods -A
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
cadvisor             cadvisor-ghq7f                               1/1     Running   0          7s
kube-system          coredns-565d847f94-24jl2                     1/1     Running   0          49s
kube-system          coredns-565d847f94-2qvqs                     1/1     Running   0          49s
kube-system          etcd-kind-control-plane                      1/1     Running   0          63s
kube-system          kindnet-f9ddq                                1/1     Running   0          49s
kube-system          kube-apiserver-kind-control-plane            1/1     Running   0          62s
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   0          61s
kube-system          kube-proxy-sftsb                             1/1     Running   0          49s
kube-system          kube-scheduler-kind-control-plane            1/1     Running   0          61s
local-path-storage   local-path-provisioner-684f458cdd-6vxh4      1/1     Running   0          49s
```

**Comment by bobbypage** [comment]
Fixes https://github.com/google/cadvisor/issues/3193

**Comment by Creatone** [comment]
@LGTM

**Review by Creatone — APPROVED** [review]

**Comment by bobbypage** [comment]
Thanks @Creatone for testing!

**Pull request merged**
