### PR TITLE
Add basic metric structures

### PR DESCRIPTION
**Pull request by vmarmol**
@rjnagal we can start with this and iterate forward.

### CODE REVIEW

**Comment by vmarmol** [comment]
WDYT of exporting the existing metrics in this format? The concrete types we export today are useful and easy to parse for systems, but using the metrics approach will make it easier to export to other systems.

**Comment by vmarmol** [comment]
Made requested changes @rjnagal PTAL

**Comment by rjnagal** [comment]
I don't know why Jenkins is also pulling in the redis patch with yours:
status 1 and output: "storage/redis/redis.go:5:2: cannot find package \"github.com/garyburd/redigo/redis\" in any of:\n\t/usr/local/go/src/github.com/garyburd/redigo/redis...

Can you kick it again?

**Comment by vmarmol** [comment]
Travis is taking forever...my tests ran fine. Need to get Jenkins to run Travis tests for cases like this.

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
