### PR TITLE
add devices to supportedSubsystem

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
This pr is fixing https://github.com/google/cadvisor/issues/1652

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
@dashpole PTAL

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by WIZARD-CXY** [comment]
@dashpole PTAL

**Comment by dashpole** [comment]
@WIZARD-CXY, this change looks fine, but I would prefer that we coordinate on the solution we add for monitoring GPUs #1436.
I would like GPU-related PRs to wait until we have come to agreement on how we plan to move forward.

**Comment by WIZARD-CXY** [comment]
@dashpole  I think gpu-related pr and this one are actually different things, this pr is intended to fullfill the functionality of ListProcesses as it is. After all, a seemingly good function doesn't work like it claim to be is very confusing for the user IMHO.

**Comment by WIZARD-CXY** [comment]
I think this function is very basic and could be use elsewhere other than gpu, I think we don't want user use this function and says "ah, it does not work, why???"

**Comment by dashpole** [comment]
@WIZARD-CXY what is the impact for end users?  Where does this information surface?  Sorry, I dont have a ton of bandwidth for looking into this...

**Comment by WIZARD-CXY** [comment]
@dashpole the issue #1652 gives a detail of this

**Comment by dashpole** [comment]
> After all, a seemingly good function doesn't work like it claim to be is very confusing for the user IMHO.

**Comment by WIZARD-CXY** [comment]
"Can you shed some more light on how this impacts users?"

As the issue said, the user can't use ListProcesses method of dockerContainerHandler. When I want to get a container's pid, ListProcesses method always return empty slice. After some digging,I found it uses fsCgroup to get the pids as the code below said https://github.com/google/cadvisor/blob/master/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go#L234. It uses devices subsytem to get pid. But in cadvisor the devices subsytem is not supported https://github.com/google/cadvisor/blob/master/container/libcontainer/helpers.go#L76. So ListProcesses will never work. Adding devices substem works fine, tested ok on my machine. 

This function is never used elsewhere in cadvisor so it explains why nobody has noticed it would never work. Other place like api uses other method (exec a ps command and analyze its output as result) as func (c *containerData) GetProcessList(cadvisorContainer string, inHostNamespace bool) ([]v2.ProcessInfo, error) defined.

**Comment by WIZARD-CXY** [comment]
@dashpole I understand your concern, my intension is just to make the function work, if it is an intented omission now then I will withdraw this pr

**Comment by dashpole** [comment]
Ok, I have had time to dig into this a little bit more, and I would prefer leaving it the way it is, unless we have a more substantial reason to change it.
`GetCgroupSubsystems` is used by the docker, rkt, and raw handlers to get cgroup paths, as well as the raw container watcher.
We currently detect cgroups that belong to containers [using a regex](https://github.com/google/cadvisor/blob/master/container/docker/factory.go#L160), and we have run into issues in the past with some cgroups being mistaken for containers.
I am surprised that ListProcesses exists, if it isnt used.  It looks like it wasnt used even when it was first added...

**Pull request closed without merging**
