### PR TITLE
Add system uuid and machine id information

### PR DESCRIPTION
**Pull request by simon3z**

### CODE REVIEW

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
LGTM thanks for the change @simon3z! When you have time, could you please sign the CLA? Once that's done we can merge.

**Comment by simon3z** [comment]
@vmarmol I am covered by the Red Hat CLA as far as I know, I commit to kubernetes already (still it seems that the bot has a problem recognizing me)

**Comment by vmarmol** [comment]
Thanks for letting me know! I didn't see you in the RedHat org.

**Comment by rjnagal** [comment]
@simon3z Can I change the semantic for machine-id a bit:

- Make the default value for machine-id as empty.
- if user sets a machine-id flag, use that.
- Use /etc/machine-id if flag is not set.
- if /etc/machine-id doesn't exist, use /var/lib/dbus/machine-id
- return empty if none of these files exist.

This will add a machine id to other distros like ubuntu without requiring flag to be changed. SG?

**Comment by vmarmol** [comment]
WDYT of making the flag accept a list of values where to look for the machine-id and make the default values /etc/machine-id and /var/lib/dbus/machine-id. Thus we check both and take the first, if none exists we leave empty.

**Comment by rjnagal** [comment]
@vmarmol that would work too. Let me do that.

**Pull request merged**
