### PR TITLE
deps: update runc to 1.1.0-rc.1

### PR DESCRIPTION
**Pull request by kolyshkin**
runc 1.1.0-rc.1 was just released. This PR updates vendored runc/libcontainer
and modifies the code according to the changes in the libcontainer API.

Since the final 1.1.0 is supposed to be very similar (if not identical), I guess this could
be merged as is (if no issues are found).

The changes to the code are:

 - resctrl: use intelrtd.Root instead of GetIntelRdtPath (which was
   removed);

 - resctrl: test: set cgroups.TestMode = true in TestGetPids (since
   by default cgroup drivers check they open cgroupfs files);

 - container/libcontainer/helpers: modify NewCgroupManager for the
   updated fs[2].NewManager API.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Note I am also testing this in kubernetes: https://github.com/kubernetes/kubernetes/pull/107016.

**Comment by iwankgb** [comment]
LGTM

**Review by iwankgb — APPROVED** [review]

**Comment by bobbypage** [comment]
This looks good, but there's a few conflicts in go.{sum,mod} files

**Comment by kolyshkin** [comment]
Rebased; PTAL @bobbypage

**Comment by bobbypage** [comment]
LGTM, thanks!

**Pull request merged**
