### PR TITLE
Fix flags typo

### PR DESCRIPTION
**Pull request by caiocfer**
Found typo when building cAdvisor that was preventing Perf event metrics from being available.
And tags were passed to build as "-tags=-tags=libfpm,netgo,libipmctl".

### CODE REVIEW

**Review by iwankgb — DISMISSED** [review]

**Comment by iwankgb** [comment]
@caiocfer merge `master` to your branch, please.

**Comment by bobbypage** [comment]
This has broke the build:

```
#18 [build 12/12] RUN export GO_TAGS="libpfm,netgo";     if [ "$(uname --machine)" = "x86_64" ]; then           export GO_TAGS="$GO_TAGS,libipmctl";     fi;     GO_FLAGS="-tags=$GO_TAGS" ./build/build.sh
#18 1.099 >> building cadvisor
#18 122.5 # github.com/google/cadvisor/perf
#18 122.5 ../perf/collector_libpfm.go:256:34: cannot use _Ctype_ulong(unsafe.Sizeof(unix.PerfEventAttr{})) (constant 128 of type _Ctype_ulong) as _Ctype_uint value in argument to (_Cfunc__CMalloc)
#18 122.5 ../perf/collector_libpfm.go:258:61: cannot use _Ctype_ulong(unsafe.Sizeof(unix.PerfEventAttr{})) (constant 128 of type _Ctype_ulong) as _Ctype_uint value in variable declaration
#18 122.5 ../perf/collector_libpfm.go:272:15: cannot use _Ctype_ulong(unsafe.Sizeof(event)) (constant 24 of type _Ctype_ulong) as _Ctype_uint value in assignment
#18 ERROR: process "/bin/sh -c export GO_TAGS=\"libpfm,netgo\";     if [ \"$(uname --machine)\" = \"x86_64\" ]; then           export GO_TAGS=\"$GO_TAGS,libipmctl\";     fi;     GO_FLAGS=\"-tags=$GO_TAGS\" ./build/build.sh" did not complete successfully: exit code: 1
------
 > [build 12/12] RUN export GO_TAGS="libpfm,netgo";     if [ "$(uname --machine)" = "x86_64" ]; then           export GO_TAGS="$GO_TAGS,libipmctl";     fi;     GO_FLAGS="-tags=$GO_TAGS" ./build/build.sh:
#18 1.099 >> building cadvisor
#18 122.5 # github.com/google/cadvisor/perf
#18 122.5 ../perf/collector_libpfm.go:256:34: cannot use _Ctype_ulong(unsafe.Sizeof(unix.PerfEventAttr{})) (constant 128 of type _Ctype_ulong) as _Ctype_uint value in argument to (_Cfunc__CMalloc)
#18 122.5 ../perf/collector_libpfm.go:258:61: cannot use _Ctype_ulong(unsafe.Sizeof(unix.PerfEventAttr{})) (constant 128 of type _Ctype_ulong) as _Ctype_uint value in variable declaration
#18 122.5 ../perf/collector_libpfm.go:272:15: cannot use _Ctype_ulong(unsafe.Sizeof(event)) (constant 24 of type _Ctype_ulong) as _Ctype_uint value in assignment
------
Dockerfile:43
--------------------
  42 |     # libipmctl only works on x86_64 CPUs.
  43 | >>> RUN export GO_TAGS="libpfm,netgo"; \
  44 | >>>     if [ "$(uname --machine)" = "x86_64" ]; then \
  45 | >>>           export GO_TAGS="$GO_TAGS,libipmctl"; \
  46 | >>>     fi; \
  47 | >>>     GO_FLAGS="-tags=$GO_TAGS" ./build/build.sh
  48 |
--------------------
ERROR: failed to solve: process "/bin/sh -c export GO_TAGS=\"libpfm,netgo\";     if [ \"$(uname --machine)\" = \"x86_64\" ]; then           export GO_TAGS=\"$GO_TAGS,libipmctl\";     fi;     GO_FLAGS=\"-tags=$GO_TAGS\" ./build/build.sh" did not complete successfully: exit code: 1
make: *** [Makefile:69: release] Error 1
```

**Comment by caiocfer** [comment]
Are you on a specific branch? Just tried to build and it went fine:
```
 => [build  7/12] ADD go.mod go.sum ./                                                                                              0.0s  => [build  8/12] RUN go mod download                                                                                              31.8s 
 => [build  9/12] ADD cmd/go.mod cmd/go.sum ./cmd/                                                                                  0.1s 
 => [build 10/12] RUN cd cmd && go mod download                                                                                    40.5s 
 => [build 11/12] ADD . .                                                                                                           0.4s 
 => [build 12/12] RUN export GO_TAGS="libpfm,netgo";     if [ "$(uname --machine)" = "x86_64" ]; then           export GO_TAGS="$  32.0s
 => [stage-1 3/5] COPY --from=build /usr/local/lib/libpfm.so* /usr/local/lib/                                                       0.1s 
 => [stage-1 4/5] COPY --from=build /usr/local/lib/libipmctl.so* /usr/local/lib/                                                    0.1s
 => [stage-1 5/5] COPY --from=build /go/src/github.com/google/cadvisor/_output/cadvisor /usr/bin/cadvisor                           0.2s
 => exporting to image                                                                                                              0.3s
 => => exporting layers                                                                                                             0.2s
 => => writing image sha256:a465c09300cfa83556bde90ce013fe9c544aaa6f4ceccd9548be74a437e9d310                                        0.0s
 => => naming to docker.io/caio/cadvisor:beta 
```

**Pull request merged**
