### PR TITLE
Switch to klog v2

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
xref : https://github.com/kubernetes/kubernetes/issues/89961

**Comment by dashpole** [comment]
Is this still WIP?  It lgtm

**Comment by dims** [comment]
@dashpole y, will ping once we have the ducks lined up in a row (need to switch to v2.0.0 from the rc1 as well)

**Comment by dims** [comment]
@dashpole this is ready!

**Pull request merged**
