### PR TITLE
Setup necessary env variables for e2e. Also, don't run tests for trivial...

### PR DESCRIPTION
**Pull request by vmarmol**
... changes.

### CODE REVIEW

**Comment by rjnagal** [comment]
Is this expected to fail?

can't load package: package github.com/google/cadvisor/integration/runner: cannot find package

**Comment by vmarmol** [comment]
Working on fixing it. It's the first real run.

**Comment by vmarmol** [comment]
@rjnagal all tests pass :) the e2e were even faster than Travis :P

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
