### PR TITLE
pointers that reference addresses of the internal circular buffer should not escape

### LINKED ISSUE #628: data race in v0.10.1
running with kubernetes kubelet integration. FWIW from my (very brief) review of the v0.11 code I think it's likely that the problem exists there too.

```
WARNING: DATA RACE
Write by goroutine 20:
  github.com/google/cadvisor/storage/memory.(*containerStorage).AddStats()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/storage/memory/memory.go:41 +0x1e1
  github.com/google/cadvisor/storage/memory.(*InMemoryStorage).AddStats()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/storage/memory/memory.go:87 +0x2b3
  github.com/google/cadvisor/manager.(*containerData).updateStats()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:319 +0xb23
  github.com/google/cadvisor/manager.(*containerData).housekeepingTick()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:241 +0x3e
  github.com/google/cadvisor/manager.(*containerData).housekeeping()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:195 +0x2bd

Previous read by goroutine 62:
  github.com/google/cadvisor/manager.(*manager).GetFsInfo()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/manager.go:585 +0x332
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).DockerImagesFsInfo()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:117 +0xad
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*realImageManager).GarbageCollect()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/image_manager.go:176 +0x97
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.func·007()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:517 +0x91
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x61
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbf
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x48
```

### PR DESCRIPTION
**Pull request by jdef**
fixes #628

### CODE REVIEW

**Comment by jdef** [comment]
I signed it! james dot defelice at ishisystems dot com

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/200

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
Thanks for the patch @jdef! and nice debugging :)

We went the ring buffer route to reduce allocations (we were using a list before) and having a ring buffer of pointers is going back to that. The alternative is copying the elements we return, but that also incurs arguably more allocations and realistically we're doing queries a lot on this data. The approach you have here is the better one I think. LGTM.

**Pull request merged**
