### PR TITLE
Fixed topology with offline CPUs on x86

### LINKED ISSUE #2566: Wrong CPU count on x86_64
It is still an issue, apparently: https://github.com/kubernetes/kubernetes/issues/89859

CC: @katarzyna-z

### PR DESCRIPTION
**Pull request by iwankgb**
It hopefully and ultimately fixes #2566. Works on x86_64. More checks pending.

CC: @bentheelder

### CODE REVIEW

**Comment by iwankgb** [comment]
There are still issues on ARM:
```
[root@dfw2-c2 cadvisor]# echo 0 > /sys/devices/system/cpu/cpu5/online
[root@dfw2-c2 cadvisor]# echo 0 > /sys/devices/system/cpu/cpu2/online
[root@dfw2-c2 cadvisor]# make build && ./cadvisor
>> building assets
>> building binaries
>> building cadvisor
W0609 21:03:48.736150   13899 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
E0609 21:03:48.860350   13899 machine.go:252] Cannot open /sys/bus/cpu/devices/cpu2/topology/core_id, number of unique core_id  set to 0
E0609 21:03:48.860386   13899 machine.go:71] Cannot read number of physical cores correctly, number of cores set to 0
E0609 21:03:48.862627   13899 machine.go:252] Cannot open /sys/bus/cpu/devices/cpu2/topology/physical_package_id, number of unique physical_package_id  set to 0
E0609 21:03:48.862656   13899 machine.go:85] Cannot read number of sockets correctly, number of sockets set to 0
^CI0609 21:03:52.569477   13899 manager.go:1157] Exiting thread watching subcontainers
I0609 21:03:52.569522   13899 manager.go:393] Exiting global housekeeping thread
I0609 21:03:52.569552   13899 cadvisor.go:243] Exiting given signal: interrupt
[root@dfw2-c2 cadvisor]# uname -a
Linux dfw2-c2.large.arm-01 4.14.0-115.2.2.el7a.aarch64 #1 SMP Wed Nov 28 22:05:51 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```
(this is Ampere eMAG 8180, on Raspberry Pi 4 it seems to be even worse).

**Comment by iwankgb** [comment]
@bentheelder, x86_64 part should work and can be tested.

**Comment by BenTheElder** [comment]
testing shortly :eyes:

**Comment by BenTheElder** [comment]
I see: `"num_cores":5,"num_physical_cores":6,"num_sockets":1,`
versus:
```
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE    MAXMHZ    MINMHZ
  0    0      0    0 0:0:0:0          yes 4000.0000 1200.0000
  1    0      0    1 1:1:1:0          yes 4000.0000 1200.0000
  2    0      0    2 2:2:2:0          yes 4000.0000 1200.0000
  3    0      0    3 3:3:3:0          yes 4000.0000 1200.0000
  4    0      0    4 4:4:4:0          yes 4000.0000 1200.0000
  5    0      0    5 5:5:5:0          yes 4000.0000 1200.0000
  6    -      -    - :::               no 4000.0000 1200.0000
  7    -      -    - :::               no 4000.0000 1200.0000
  8    -      -    - :::               no 4000.0000 1200.0000
  9    -      -    - :::               no 4000.0000 1200.0000
 10    -      -    - :::               no 4000.0000 1200.0000
 11    -      -    - :::               no 4000.0000 1200.0000
```

**Comment by BenTheElder** [comment]
> W0609 19:03:27.643460 3221212 sysfs.go:340] unable to read /sys/devices/system/node/node0/cpu0/online: open /sys/devices/system/node/node0/cpu0/online: no such file or directory

**Comment by iwankgb** [comment]
Sounds legit, making 0 CPU offline might not be a very good idea.

**Comment by dghubble** [comment]
I see expected counts on my (SMT disabled) system again: `"num_cores": 1, "num_physical_cores": 1, "num_sockets": 1` :+1:

**Comment by BenTheElder** [comment]
thank you! working on an update PR for kubernetes

**Pull request merged**
