### PR TITLE
Fix Prometheus metrics and typo in container info stats

### PR DESCRIPTION
**Pull request by juliusv**
I also plan on following this up with a larger refactoring of the Prometheus metrics part, as well as adding tests to that.

### CODE REVIEW

**Comment by juliusv** [comment]
@discordianfish @vmarmol

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
Thanks for the fixes @juliusv! LGTM, will merge on green.

**Comment by juliusv** [comment]
Oh wait, I squashed some followup fixes into the wrong commit - will fix in a second.

**Comment by juliusv** [comment]
Ok, should be all good now.

**Comment by vmarmol** [comment]
Thanks! Waiting on Jenkins.

**Pull request merged**
