### PR TITLE
Replace use of cgo for getting number of online CPUs

### PR DESCRIPTION
**Pull request by lorenz**
This is part of a series of PRs removing the dependence on cgo for cadvisor. Together with https://github.com/mindprince/gonvml/pull/11 and a forthcoming PR for the cpuload collector all of cadvisor and kubelet are buildable without cgo.

### CODE REVIEW

**Comment by lorenz** [comment]
@dashpole Could you have a quick look at the e2e test failure? To me it looks like an internal failure, but I'm not familiar enough with the K8s E2E framework to know for sure.

**Comment by dashpole** [comment]
make all
I0513 16:28:54.459] >> vetting code
W0513 16:29:02.996] # github.com/google/cadvisor/container/libcontainer
W0513 16:29:02.997] container/libcontainer/handler.go:515:20: undefined: unix.CPUSet
W0513 16:29:02.997] container/libcontainer/handler.go:516:12: undefined: unix.SchedGetaffinity
W0513 16:29:06.029] # github.com/google/cadvisor/container/libcontainer [github.com/google/cadvisor/container/libcontainer.test]
W0513 16:29:06.029] container/libcontainer/handler.go:515:20: undefined: unix.CPUSet
W0513 16:29:06.029] container/libcontainer/handler.go:516:12: undefined: unix.SchedGetaffinity

**Comment by lorenz** [comment]
Oh, you're right. This depends on https://github.com/google/cadvisor/pull/2239/commits/9fdea2af96c16fd2925e24a9c42f5762f3e6a55e which is part of the other PR. Should I rebase this on top of the other PR (so there is only one PR) or should I just wait until the other one is merged in and then rebase this one on the new master?

**Comment by dashpole** [comment]
Yeah, you can add this as a commit on the other PR.

**Pull request closed without merging**
