### PR TITLE
Porting fixes to #2792 and #2798 to v0.38

### PR DESCRIPTION
**Pull request by iwankgb**
Porting of recent fixes applied to master.

### CODE REVIEW

**Comment by iwankgb** [comment]
@Creatone can you add a consent comment, please?

**Comment by Creatone** [comment]
@googlebot I consent.

**Comment by Creatone** [comment]
@googlebot I consent.

**Comment by bobbypage** [comment]
Why is the `libimpctl` dockerfile change needed to be cherrypicked? That seems more like a feature rather than a bug fix, so I think that makes sense more sense for the next minor version.

**Comment by iwankgb** [comment]
@bobbypage it shouldn't have been, you are completely right :)

**Comment by bobbypage** [comment]
@iwankgb np, thanks for putting the cherrypick together.

**Comment by bobbypage** [comment]
https://github.com/google/cadvisor/releases/tag/v0.38.8 has been cut with this included.

**Pull request merged**
