### PR TITLE
Godeps: revendor packags with more up-to-date godep version

### LINKED ISSUE #1161: Godeps in bad state?
Trying to help @sjpotter with his rkt work on this project and we're having issues with godep.

At the moment, running `godep restore && godep save ./...` currently adds a bunch of aws packages that seem to be missed.

```
$ go version
go version go1.5.3 linux/amd64
$ godep version
godep v57 (linux/amd64/go1.5.3)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ godep restore
$ godep save ./...
godep: WARNING: Recorded go version (go1.5.3) with minor version string found.
godep: To record current major go version run `godep update -goversion`.
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Godeps/Godeps.json
	deleted:    Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
	deleted:    Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/seccomp/fixtures/proc_self_status

no changes added to commit (use "git add" and/or "git commit -a")
```

`Godeps/Godeps.json` has a huge diff (adds ~20 packages). The diff can be found [here](https://gist.github.com/ericchiang/34fba67d4e09aade8bbe)

Should we open a PR to rectify this?

### PR DESCRIPTION
**Pull request by ericchiang**
Closes #1161

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by ericchiang** [comment]
What's a good way to add `go get golang.org/x/tools/cmd/vet` to the Jenkins build? :)

**Comment by vishh** [comment]
What version of godeps was used?

**Comment by ericchiang** [comment]
```
$ godep version
godep v57 (linux/amd64/go1.5.3)
```

Should we record this somewhere?

**Comment by vishh** [comment]
Yeah. Given that godep is not compatible across versions, we should document it.

**Comment by vishh** [comment]
This PR LGTM. Merging it..

**Pull request merged**
