### PR TITLE
fix kubernetes issue #65204

### PR DESCRIPTION
**Pull request by MaximilianMeister**
https://github.com/kubernetes/kubernetes/issues/65204

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
@googlebot I signed it!

**Comment by dashpole** [comment]
This looks reasonable to me, although it makes the brtfs-specific code even more complex.
cc @flavio @dmrub who have made improvements to this in the past in-case (and likely are more familiar with brtfs than I am), in-case they have any comments

**Comment by flavio** [comment]
@dashpole the change looks good to me. I worked with @MaximilianMeister on that ;)

**Pull request merged**
