### PR TITLE
Porting fixes to #2743 and #2783 to 0.37

### PR DESCRIPTION
**Pull request by iwankgb**
For details see:

- #2743
- #2783
- #2813

It will allow us to get kubernetes/kubernetes#95039 fixed.

### CODE REVIEW

**Comment by iwankgb** [comment]
@kgtw we need your consent to merge this PR.

**Comment by iwankgb** [comment]
@kgtw I guess it must be a new comment.

**Comment by kgtw** [comment]
@googlebot I consent

**Review by bobbypage — APPROVED** [review]

**Comment by bobbypage** [comment]
LGTM

**Pull request merged**
