### PR TITLE
Add support to report container's filesystem stats

### PR DESCRIPTION
**Pull request by shilpamayanna**
This fix includes support to report container’s filesystem stats. 
Added support to identify container’s mounts and report disk statistics for the same.

### CODE REVIEW

**Comment by vishh** [comment]
@shilpamayanna Thanks for the PR. I don't think the logic is valid. Take a look at #1204 which is an attempt to add filesystem metrics support for device mapper storage backend.

**Comment by shilpamayanna** [comment]
Thanks @vishh. With this PR, we are trying to add support to obtain filesystem stats for all device files used by container. 
We can leverage the support from PR #1204 for thin-provisioned devices.
However, the implementation doesn’t seem to handle the block devices shown in the example below.
nvme1n1                     259:0    0    10G  0 disk /var/lib/kubelet/pods/d3162804-1222-11e6-9aea-2c600c82eccc/volumes/datawise.io~volume/data
nvme2n1                     259:1    0    10G  0 disk /var/lib/kubelet/pods/d30a9040-1222-11e6-9aea-2c600c82eccc/volumes/datawise.io~volume/data

Could you please let me know if there is any active work around this area to obtain stats for these devices?

**Comment by vishh** [comment]
@shilpamayanna IIUC, you intend to add support for getting stats for volumes mounted into containers. Given that volumes are essentially mounts, there is no guarantee that these mounts will be backed by devices. They can be arbitrary directories on disk, that are potentially shared between containers.

If you are using kubernetes, take a look at the output of summary API - `http://localhost:10255/stats/summary` on your nodes. Kubelet collects volumes stats. We can extend that to collect stats for your volume type easily. Its basically a TODO.

**Comment by shilpamayanna** [comment]
@vishh Thanks for the reply. There is a check to ensure that the statistics are retrieved for block devices only and other mounts that are not backed by devices are skipped. If the mounts are shared between containers, the stats are collected for all the containers sharing the device.

Summary API provides metrics for the filesystem usage and capacity only. 
Is there a plan to add support for disk metrics?

**Comment by vishh** [comment]
@shilpamayanna This PR is incompatible with the v2 version of the API. In v2, [`Filesystem`](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L293) stats do not include Disk metrics. We decided to expose disk metrics as part of the entire machine only. 

Why do you need disk stats for volumes?

**Comment by shilpamayanna** [comment]
@vishh We use disk stats to calculate IOPs used by containers. Is there any other way to compute IOPs?

**Comment by vishh** [comment]
@shilpamayanna [DiskIO](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L301) stats are already exposed per container.

**Comment by shilpamayanna** [comment]
@vishh Thanks for the providing the pointers. I observed that DiskIO stats reported contains device major and minor number. In a cluster with multiple nodes, these numbers could overlap across nodes. We need a way to map these stats to the volume. May be container’s mountpoint would help. 

Also it would be helpful to export the DiskIO stats to heapster.

**Comment by vishh** [comment]
@shilpamayanna As part of overall machine stats you get a dump of all devices with major and minor. You can use that information to identify devices.

I'd suggest opening an issue against heapster to support DiskIO stats.

**Comment by shilpamayanna** [comment]
@vishh Thanks. Will open issue against heapster. 
How can I get the machine stats?

**Comment by vishh** [comment]
`/api/v2.1/machinestats`

**Comment by vishh** [comment]
I'm closing this PR under the assumption that there is no change required from cAdvisor. Feel free to re-open if you disagree @shilpamayanna!

**Pull request closed without merging**
