### PR TITLE
use sdjournal instead of journalctl for oom parsing

### PR DESCRIPTION
**Pull request by sjenning**
Addresses kube issue https://github.com/kubernetes/kubernetes/issues/34965

Alternative to #1544

Use `github.com/coreos/go-systemd/sdjournal` instead of exec'ing `journalctl -f -k` and leaking the process.

_NOTE_: Using sdjournal requires the systemd headers be installed on the compiling system.  For EL distros that is `yum install systemd-devel`.

@derekwaynecarr @eparis @euank @dchen1107 @vishh @adohe

### CODE REVIEW

**Comment by sjenning** [comment]
cc @jsafrane

**Comment by derekwaynecarr** [comment]
our queue of cadvisor updates is growing, need to track down e2e problems.

**Comment by dashpole** [comment]
@sjenning please rebase.  The infra issue should be fixed

**Comment by sjenning** [comment]
@dashpole so it hit the new dependency on systemd-devel I mentioned in the PR description.

```
I0801 19:30:09.573] >> building cadvisor
W0801 19:30:11.299] # github.com/google/cadvisor/vendor/github.com/coreos/go-systemd/sdjournal
W0801 19:30:11.300] vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:33: fatal error: systemd/sd-journal.h: No such file or directory
W0801 19:30:11.300]  // #include <systemd/sd-journal.h>
W0801 19:30:11.300]                                  ^
```

Can you add the distro appropriate package to the builder?

**Comment by euank** [comment]
If we're planning to switch to directly parsing kmsg instead, I don't see why this change is necessary.

**Comment by sjenning** [comment]
@euank at the time I submitted this, that PR hadn't moved since mid-March. I did note that this was an alternative to https://github.com/google/cadvisor/pull/1544

Only one need be accepted, but one _does_ need to be accepted.

**Comment by sjenning** [comment]
It looks like both of these approaches (sdjounal and reading /dev/kmsg) are used in NPD.
https://github.com/kubernetes/node-problem-detector/blob/master/pkg/systemlogmonitor/logwatchers/kmsg/log_watcher.go
https://github.com/kubernetes/node-problem-detector/blob/master/pkg/systemlogmonitor/logwatchers/journald/log_watcher.go

@dchen1107 just mentioned this as a way during a sig-node meeting, so I wrote it up.

**Comment by sjenning** [comment]
closed in favor of https://github.com/google/cadvisor/pull/1729

**Pull request closed without merging**
