### PR TITLE
Porting fixes to #2792 and #2798 to v0.37

### PR DESCRIPTION
**Pull request by iwankgb**
Porting of recent fixes applied to master.

### CODE REVIEW

**Comment by iwankgb** [comment]
@Creatone can you add a comment in this PR too, please?

**Comment by Creatone** [comment]
@googlebot I consent.

**Comment by bobbypage** [comment]
LGTM, thanks for both your work on this!

**Comment by bobbypage** [comment]
https://github.com/google/cadvisor/releases/tag/v0.37.5 has been cut with this included.

**Pull request merged**
