### PR TITLE
ClockSpeed not defined in /proc/cpuinfo for AArch64, so return 0.

### PR DESCRIPTION
**Pull request by yghannam**
Signed-off-by: Yazen Ghannam <yazen.ghannam@linaro.org>

### CODE REVIEW

**Comment by jimmidyson** [comment]
I wonder if we'd be better using build constraints for stuff like this? Tiny performance improvement, but possibly worth exploring in this case.

**Comment by yghannam** [comment]
CLA signed through Linaro.

@jimmidyson 
This fixes a runtime error so I'm not sure that a build constraint will be easy to do in this case. I think there may be some other parts that expect machineInfo.CpuFrequency to be defined.

**Comment by jimmidyson** [comment]
@yghannam Understood. LGTM. Thanks very much!

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
Merging. Thanks @yghannam!

**Pull request merged**
