### PR TITLE
Updating containerd version

### PR DESCRIPTION
**Pull request by eweber9858**
In order to vendor in this PR [(microsoft/hcsshim#730)](https://github.com/microsoft/hcsshim/pull/730) to kubernetes, the containerd/containerd dependency must also be upgraded to a newer version (github.com/containerd/containerd v1.3.0-beta.2.0.20190828155532-0293cbd26c69). This newer version is incompatible with google/cadvisor because of this [commit](https://github.com/containerd/containerd/commit/927517de3696b147923dedda385b0f9e705afda5#), where the github.com/containerd/containerd/dialer package was moved to github.com/containerd/containerd/pkg/dialer. This change in path is disruptive to google/cadvisor because the dialer package is imported in container/containerd/client.go.

This PR bumps the containerd version to v1.2.0, which is one of the earliest releases of containerd with the needed change (another option is to bump to the latest version, v1.3.2)

### CODE REVIEW

**Comment by eweber9858** [comment]
@dashpole PTAL

**Comment by dashpole** [comment]
cc @Random-Liu

**Comment by dashpole** [comment]
You will need to rebase on top of #2370 to fix the test.

**Comment by dashpole** [comment]
This should no longer be needed.  The containerd version was updated past this point in https://github.com/google/cadvisor/pull/2372

**Pull request closed without merging**
