### PR TITLE
Update gonvml to workaround bazelbuild/rules_go#1003.

### PR DESCRIPTION
**Pull request by mindprince**

### CODE REVIEW

**Comment by mindprince** [comment]
Without this bazel tests were failing in https://github.com/kubernetes/kubernetes/pull/55188.

/cc @dashpole

**Comment by dashpole** [comment]
Would you like me to merge this, or do you want another set of eyes for the nvml changes?

**Comment by mindprince** [comment]
I think they are good to be merged. But cc'ing @vishh and @jiayingz just in case.

**Pull request merged**
