### PR TITLE
Docker client update including reuse

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Also fixes #929

**Comment by vishh** [comment]
Other than the outstanding comment, this PR LGTM.

Thanks a lot @jimmidyson for this PR! :)

**Comment by jimmidyson** [comment]
Switched to `sync.Once` as suggested by @vishh. This will not try to recreate client if it ever fails but I think that's OK.

**Comment by vishh** [comment]
My bad. I forgot about a change that I have been meaning to do. 
As of now cAdvisor requires docker daemon to be up before it starts up. I want to change this behavior soon, because it makes kubelet internal architecture complex. 
I'm OK with this PR for now, and altering the current behavior should be easy in the future thanks to this PR!

**Comment by vishh** [comment]
Ignore my previous comment. Since client creation does not require the daemon to be up, as long as client creation doesn't fail, we should be fine. Sorry about the noise!

**Comment by vishh** [comment]
LGTM.

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
`sync.Once` looks good. Thanks for fixing this!

**Comment by dchen1107** [comment]
@jimmidyson Are you going to cut a release with this one or you want to include devicemapper fix too?

**Comment by jimmidyson** [comment]
@dchen1107 I want the devicemapper enhancement too if you're OK to wait?

**Pull request merged**
