### PR TITLE
Move StatsBuffer to be time-based

### PR DESCRIPTION
**Pull request by vmarmol**
This is the first step in making StatsBuffer non-stats specific and usable elsewhere. There are some further simplifications we can make to the code which I will do in future PRs.

### CODE REVIEW

**Comment by rjnagal** [comment]
Does this flag applies to stats as well as events?

**Comment by vmarmol** [comment]
Stats, events will have a separate flag.

**Comment by rjnagal** [comment]
LGTM

**Comment by rjnagal** [comment]
event tests failed.

**Comment by vmarmol** [comment]
I think those tests are broken at HEAD:

http://104.154.52.74/job/cadvisor-e2e/812/console

that's from a clean client. Let me try to debug.

**Comment by vmarmol** [comment]
Rebased, Travis is green and Jenkins passes: http://104.154.52.74/job/cadvisor-e2e/821/console

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
