### PR TITLE
Implement Splunk Storage Driver

### PR DESCRIPTION
**Pull request by outcoldman**
Allow to send stats to Splunk Enterprise or Splunk Cloud instance using splunk storage driver.

### CODE REVIEW

**Comment by outcoldman** [comment]
I signed it!

**Comment by outcoldman** [comment]
Our company Splunk Inc. has signed Contributor License Agreement

**Comment by outcoldman** [comment]
ping @timstclair 
seems like bot got stuck, as it took me too long to reply "I signed it!"

**Comment by timstclair** [comment]
It looks like our system still thinks you haven't signed the CLA. Did you commit with your company email address?

**Comment by outcoldman** [comment]
@timstclair did not know it was a requirement, changed to my working email

**Comment by timstclair** [comment]
Hmm, can you try responding with "I signed it" again? Is your corp email associated with your github account (in https://github.com/settings/emails)?

**Comment by outcoldman** [comment]
I signed it!

**Comment by outcoldman** [comment]
@timstclair  yes, it is associated. I am a little bit confused by the sign process, our company signed "Google Software Grant and Corporate Contributor License Agreement" in January, but without specifying any accounts (at least not mine). Does the bot just tracks the company domain in emails?

Btw about the failure in the unit tests: in one of the unit tests I verify that storage works as expected when Splunk is not available and will retry to send stats when it will be available. Also because I specify the limit for the buffer (and retry logic) - this is why this test generates error logs. How should I handle this case?

**Comment by timstclair** [comment]
Hmm, I'm not sure exactly. I'll try to get to this review in the next ~2 weeks, and I'll look into it more then.

**Comment by outcoldman** [comment]
@timstclair awesome, thanks!

**Comment by outcoldman** [comment]
@timstclair Hey Tim, any updates on this?

**Comment by timstclair** [comment]
We're reconsidering how we want to handle storage drivers in cAdvisor right now (see https://github.com/google/cadvisor/issues/1458). For the moment, storage driver additions are on-hold.

/cc @dchen1107 @vishh

**Comment by vishh** [comment]
It might be helpful for the community to help us implement #1458. WDYT?

**Comment by outcoldman** [comment]
@vishh sure, we can take a look on that as well, when do you plan to switch to 1.8, right after release?

**Comment by timstclair** [comment]
I commented on that issue. I think the resolution is more complicated than I initially thought, but unfortunately I don't have the time to think through it right now.

**Pull request closed without merging**
