### PR TITLE
Introducing linter

### PR DESCRIPTION
**Pull request by iwankgb**
The goal of this PR is to have liner run on each build to ensure that code meets certain quality standards. The PR will probably grow quite huge but it's based on `golangci-lint` feedback and cAdvisor should not built if something goes wrong.

### CODE REVIEW

**Comment by iwankgb** [comment]
@dashpole, I know it's sort of large but it includes only _simple_ fixes such as:
* renamed identifiers
* not using `self` or `this` as receiver name
* stuttering
* etc

All other issues have been ignored and clearly marked in `golangci.yml`.

**Comment by iwankgb** [comment]
For the record: I know it's huge, I hate PRs of this size myself. I can try to cut it into pieces if you want.

**Comment by iwankgb** [comment]
There will be follow-up. This must be closed, though.

**Comment by dashpole** [comment]
oh, ok.

**Pull request closed without merging**
