### PR TITLE
Bump godep for go-dockerclient

### PR DESCRIPTION
**Pull request by pmorie**
Needed to pull in graphdriver support

@vishh @sjenning

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by vishh** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@vishh light is green, trap is clean :ghost:

**Pull request merged**
