### PR TITLE
chore: update go.mod to 1.18

### PR DESCRIPTION
**Pull request by akhilerm**
- update go.mod in root and cmd/ to 1.18
- versions of dependencies are not updated. only the indirect dependencies are added to the go.mod file

Signed-off-by: Akhil Mohan <makhil@vmware.com>

### CODE REVIEW

**Comment by akhilerm** [comment]
PTAL @dims @bobbypage

**Comment by akhilerm** [comment]
@bobbypage @dims Can you take a look at this PR?

**Comment by bobbypage** [comment]
Sorry for delay, I don't fully understand why there are so many changes to the `go.mod` file? What set of commands were used to update it?

**Comment by akhilerm** [comment]
Since go1.17, indirect dependencies are kept in separate `require` block. Ref: https://go.dev/doc/go1.17#go-command
Only `go mod tidy` has been run after updating the go version.

**Pull request closed without merging**
