### PR TITLE
Limit the number of events stored to 24h.

### PR DESCRIPTION
**Pull request by vmarmol**
There is a TODO to make this configurable.

### CODE REVIEW

**Comment by rjnagal** [comment]
Why do it by time? The most common case we want to avoid is the crashlooping containers flooding events.

**Comment by vmarmol** [comment]
We've been moving to time based since its easier to reason about (we keep all events for the last 24hrs rather than the last 1000 events). Alternative we can have some policy to rate-limit the errors or place an absolute limit as well as a time limit. WDYT? We can do either of those in another PR since this one makes the current situation strictly better :)

**Comment by rjnagal** [comment]
This is better than what we have. But the memory bounds are still worrisome. I'd say we should place an absolute limit based on amount of memory we need to store these.

**Comment by rjnagal** [comment]
Can you also look at the test failure to see if its related?

**Comment by vmarmol** [comment]
@rjnagal PTAL, all tests pass. The error was on the CI side, the machines had a bunch of leftover crud.

**Comment by vmarmol** [comment]
I will followup this PR with an absolute limit.

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
