### PR TITLE
[0.45] Request the pid of another container if current pid is not longer valid

### PR DESCRIPTION
**Pull request by harche**
This PR backports the changes from https://github.com/google/cadvisor/pull/3301 to 0.45

### CODE REVIEW

**Comment by iwankgb** [comment]
@dims, is this something that Kubernetes needs?

**Comment by bobbypage** [comment]
/ok-to-test

@harche can you rebase this? I merged a few fixes to CI to get it green.

**Comment by harche** [comment]
> /ok-to-test
> 
> @harche can you rebase this? I merged a few fixes to CI to get it green.

Done, thanks.

**Pull request merged**
