### PR TITLE
WIP: Fix cAdvisor running in a container on RHEL platforms

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/google/cadvisor/issues/1461

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
FYI: @smarterclayton @ncdc @pmorie @mrunalp

The first commit is temporary carry for https://github.com/opencontainers/runc/pull/1049.  Once that merges, I can just drop the carry and update with a vendor dependency being updated.

I am testing this now on RHEL in container to validate it works ;-)

**Comment by mrunalp** [comment]
@derekwaynecarr Sounds good. Let me know if you run into any issues.

**Comment by derekwaynecarr** [comment]
OK -- confirmed on RHEL7 in container that this works for me.

Will update the PR when @mrunalp code merges.

**Comment by pmorie** [comment]
seems like it might be good to have 'opencontainers/runc#1049' in the commit message for the carry

**Comment by derekwaynecarr** [comment]
@pmorie -- the carry is intended to be replaced before this PR merges.  I was just holding it there for testing purposes.

**Comment by mrunalp** [comment]
@derekwaynecarr runc PR is merged now so you can pick it up.

**Comment by derekwaynecarr** [comment]
requisite runc pr has merged, will send a pr to update vendor library and then drop the first commit here.

**Comment by derekwaynecarr** [comment]
Closing this in favor of https://github.com/google/cadvisor/pull/1476

**Pull request closed without merging**
