### PR TITLE
bump containerd version to v1.5.1

### PR DESCRIPTION
**Pull request by Priyankasaggu11929**
**What this PR does / why we need it:**

This PR bumps the `containerd` version to v1.5.1

**Additional context**

Link to the new release: https://github.com/containerd/containerd/releases/tag/v1.5.1

Signed-off-by: Priyanka Saggu <priyankasaggu11929@gmail.com>

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
@googlebot I signed it!

**Comment by Priyankasaggu11929** [comment]
cc: @dims

**Comment by bobbypage** [comment]
LGTM, thanks!

**Review by bobbypage — APPROVED** [review]

**Pull request merged**
