### PR TITLE
container/crio: retry getting pid if 0

### PR DESCRIPTION
**Pull request by sjenning**
When a container is created, cadvisor creates a handler, triggered by inotify.  In the case of a crio managed container, the crio handler immediately queries crio for the pid of the just created container.  Due to performance concerns in crio, the pid might not yet be known and thus returns 0.  If the pid is 0, then network stats are not collected for the lifetime of the container or the lifetime of cadvisor, whichever is shorter.

https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go#L80-L83

This PR changes the crio handler to requery crio for the pid if the pid was unknown during handler initialization or the last `GetStat()` call.  Once the pid becomes known, the libcontainer handler with the non-zero pid is cached and no further crio queries are needed.

Fixes https://github.com/openshift/origin/issues/23492

@mrunalp @dashpole

### CODE REVIEW

**Comment by mrunalp** [comment]
:+1:

**Comment by sjenning** [comment]
fyi @Reamer

**Comment by Reamer** [comment]
Hi @sjenning,
I will try this fix today in my test environment.

**Comment by Reamer** [comment]
I think you have a small typo.
```patch
diff --git a/container/crio/handler.go b/container/crio/handler.go
index 7d0c5a83..d9eab06e 100644
--- a/container/crio/handler.go
+++ b/container/crio/handler.go
@@ -296,7 +296,7 @@ func (self *crioContainerHandler) getLibcontainerHandler() *containerlibcontaine
 	}
 
 	self.pidKnown = true
-	self.libcontainerHandler = containerlibcontainer.NewHandler(self.cgroupManager, self.rootFs, cInfo.Pid, self.ignoreMetrics)
+	self.libcontainerHandler = containerlibcontainer.NewHandler(self.cgroupManager, self.rootFs, cInfo.Pid, self.includedMetrics)
 
 	return self.libcontainerHandler
 }
```

**Comment by sjenning** [comment]
ah yes, I made this patch against origin 3.11 vendor tree and that changed in master

**Pull request merged**
