### PR TITLE
Remove Jenkins env setup

### PR DESCRIPTION
**Pull request by vmarmol**
These are now in the Jenkins config.

This is also the first PR where Jenkins will run the CI component as well.

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
Jenkins is happy. Safe to merge?

**Comment by rjnagal** [comment]
LGTM

**Comment by vmarmol** [comment]
Yep, safe to merge! Now all the tests are run by Jenkins as well.

**Pull request merged**
