### PR TITLE
Enable check for cpu load in integration tests.

### PR DESCRIPTION
**Pull request by rjnagal**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
Integration test is failing, for some reason the command is failing. Wonder if we're killing it? I'd also expect to not have the Run return though since it is running in the foreground.

**Comment by rjnagal** [comment]
It works with local docker daemon. I guess the ssh command invocation is messing up the script. I'll take a look.

**Comment by rjnagal** [comment]
Withdrawing this for now as we integrate #495

**Pull request closed without merging**
