### PR TITLE
Upgrade to blang/semver/v4 v4.0.0

### PR DESCRIPTION
**Pull request by skitt**
This is the first version to be fully go-mod-compatible.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
I’ve been added to the CCLA, I don’t know what needs to be done to re-trigger the cla/google job.

**Comment by skitt** [comment]
@dims this is related to a k8s bump which went in a while ago (https://github.com/kubernetes/kubernetes/pull/108629), and would simplify the overall dependency tree in k8s.

**Comment by dims** [comment]
for the record, the diff is : https://github.com/blang/semver/compare/v3.5.1...v4.0.0

**Comment by skitt** [comment]
@dims do you know who I should ping to try to make progress on this?

**Comment by dims** [comment]
@skitt we should reach out to @bobbypage

**Comment by skitt** [comment]
@bobbypage any chance you could take a look at this?

**Comment by skitt** [comment]
@bobbypage, @iwankgb, any chance I could get this PR reviewed? It would help the `k/k` dependency tree.

**Review by iwankgb — APPROVED** [review]

**Pull request merged**
