### PR TITLE
Link cAdvisor statically.

### PR DESCRIPTION
**Pull request by vishh**
cc @mikedanese

### CODE REVIEW

**Comment by timstclair** [comment]
What are the concerns around building this way? Is it just that it increases our shipping binary size?

**Comment by vishh** [comment]
It makes it possible to distribute cAdvisor & kubelet without requiring a
controlled base image.

**Comment by timstclair** [comment]
LGTM

**Comment by timstclair** [comment]
This won't affect kubelet though.

**Comment by vishh** [comment]
This PR won't. I'm working on a separate patch for k8s. AFAIK cAdvisor was
the main reason why we did not link statically.

**Comment by luxas** [comment]
Seems like you forgot #1237, which was opened ages ago :( and failed due to internal flakes
However, I'm glad this is in, and I've been experimenting with linking kubelet statically...

**Comment by vishh** [comment]
Oops. Apologies. I sent out the PR while discussing kubelet distribution
issues with my colleagues.
I'm happy to revert this PR in favor of #1237 :)

**Comment by luxas** [comment]
No no. This is good as-is :)
Instead, please review kubernetes/kubernetes#26028 :)

**Comment by djtm** [comment]
Ha, great. :+1:

**Pull request merged**
