### PR TITLE
Cherrypick #1369

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vishh** [comment]
cc @mtaufen @timstclair

**Comment by mtaufen** [comment]
Nice.

**Comment by mtaufen** [comment]
Chicken vs. egg problem: Jenkins GCE e2e won't pass until this goes in. :)

**Comment by timstclair** [comment]
I think we should cherry-pick https://github.com/google/cadvisor/pull/1357 instead, since it has much fewer changes and won't affect the binaries at all.

**Comment by timstclair** [comment]
The underlying issue is that we changed the jenkins jobs to use the build/jenkins_e2e.sh script, but the release-v0.23 branch doesn't have a functional version of that script.

**Comment by vishh** [comment]
That SGTM. Feel free to close this PR.

**Comment by timstclair** [comment]
Sure. @mtaufen can you do the cherry-pick?

**Comment by mtaufen** [comment]
Sure.

**Pull request closed without merging**
