### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by GlobalHelp**
Add a folder FR and EN for docs.
Translated files:
-README.md FR = 95%
-Api.md FR = 35%
-Apiv2.md  FR= 0%
-Client.md FR= 0%
-Build.md FR= 0%
-Integration Test.md  FR=0%
-Deploy.md FR =0 %
-Prometheus FR=0 %

### CODE REVIEW

**Comment by GlobalHelp** [comment]
I signed it!

**Comment by vmarmol** [comment]
Hi! The only question and concern I have is how these translations are updated when changed are made to the english version. Unfortunately, none of the maintainers are fluent in french.

**Comment by GlobalHelp** [comment]
Hi,I think there are other contributing French who can update the documents but it is true that the French version will have a few days/weeks late.

**Comment by rjnagal** [comment]
I feel that this is going to be really hard to maintain. We would need to add versioning to our documentation and the whole process.

If you would like to maintain the docs, you can host it somewhere and we can add a link to it.

Thanks for the PR.

**Comment by GlobalHelp** [comment]
OK.I understand

**Pull request closed without merging**
