### PR TITLE
Add Amazon SQS storage

### PR DESCRIPTION
**Pull request by ujovlado**

### CODE REVIEW

**Comment by ujovlado** [comment]
Any chance to review this? (cc: @vishh @timstclair )

**Comment by timstclair** [comment]
We're currently heads-down for our next release. I can take a look in a couple weeks if no one gets to it before then.

**Comment by ujovlado** [comment]
ok, great.

**Comment by ujovlado** [comment]
Hi, is there something I can help with?

**Comment by timstclair** [comment]
This is currently blocked by https://github.com/google/cadvisor/issues/1458

**Comment by ujovlado** [comment]
Oh, I didn't notice that. Thanks!

**Comment by ujovlado** [comment]
@dashpole I have one question. What is the best way when someone wants to add custom storage driver to cadvisor?

**Comment by dashpole** [comment]
Hey @ujovlado, sorry your PR didn't make it in.  Sadly, the cAdvisor team (just me right now) isn't in a position to adequately maintain storage drivers.

The prometheus endpoint is the most widely used, and best maintained endpoint, so i'd recommend relying on that if at all possible.  I briefly looked around, and didn't see any existing output plugins for common metrics processors (telegraf, opentelemetry) for amazon sqs, though.  If there were a place for such a storage plugin to live, it would probably be in one of those frameworks...

While I don't want to encourage forking, you could always maintain the storage driver separately in your fork if you just want it for your use.  Rebasing should be very simple.

Again, I'm sorry we weren't able to accept your contribution.

**Pull request closed without merging**
