### PR TITLE
Bump minimum Go version to 1.22 release

### PR DESCRIPTION
**Pull request by mythi**
Per request in https://github.com/google/cadvisor/pull/3513#issuecomment-2433422512

cc @SergeyKanzhelev

### CODE REVIEW

**Comment by kolyshkin** [comment]
I've opened #3616

**Review by iwankgb — APPROVED** [review]

**Comment by iwankgb** [comment]
Ha, we need to change CI - it should run tests on 1.23 and 1.22 now.

**Comment by kolyshkin** [comment]
> Ha, we need to change CI - it should run tests on 1.23 and 1.22 now.

As I said earlier,  https://github.com/google/cadvisor/pull/3613#issuecomment-2439145571

**Comment by mythi** [comment]
superseded by #3616

**Pull request closed without merging**
