### PR TITLE
Fix typo in libipmctl

### PR DESCRIPTION
**Pull request by katarzyna-z**
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>

### CODE REVIEW

**Review by Zenix27 — APPROVED** [review]

**Comment by Creatone** [comment]
LGTM

**Comment by iwankgb** [comment]
lgtm

**Comment by iwankgb** [comment]
@bobbypage could you merge this one too?

**Review by bobbypage — APPROVED** [review]

**Comment by bobbypage** [comment]
LGTM, thanks for the fix!

**Pull request merged**
