### PR TITLE
Fixed minor typo in runtime_options.md

### PR DESCRIPTION
**Pull request by DreadPirateShawn**

### CODE REVIEW

**Comment by vmarmol** [comment]
Thanks for the PR @DreadPirateShawn! LGTM minus the CLA. Let us know when you've had a chance to sign that :)

**Comment by vmarmol** [comment]
Ping @DreadPirateShawn  :)

**Comment by DreadPirateShawn** [comment]
Thanks -- this is in progress. I actually am engaging with cAdvisor as part of a company project, I just saw the typo before getting into any "real" work. So rather than accepting the CLA personally, I've sent this to my boss, and we're going through some minor internal hoops prior to accepting on behalf of the company. I'll eventually have approval to remove the "r" from "oftern"... :-P

**Comment by vmarmol** [comment]
lol, thankfully it was just one letter, otherwise it might take longer :)

Np, let us know.

**Comment by DreadPirateShawn** [comment]
...and done! CLA has been signed and filed, corporation name is "Skytap Inc."

**Comment by vmarmol** [comment]
I don't see it yet, but they may not have processes it yet if you submitted recently. I'll check back and let you know.

**Comment by DreadPirateShawn** [comment]
Fair enough. If it helps, it was signed / submitted / confirmed this past Friday (March 20, 2015) -- we got an email confirmation on the same day from "Google <echosign@echosign.com>" with the CLA attached, subject "Google Corporate CLA between Google and Brad Schick is Signed and Filed!", cc'ed to "Google CLA Submissions <cla-submissions@google.com>". Not sure if there are any additional internal steps pending in Google's processing pipeline.

**Comment by vmarmol** [comment]
@googlebot are you happy now?

**Comment by vmarmol** [comment]
Manually verified the CLA for Skytap. Thanks @DreadPirateShawn and sorry for the delay.

**Pull request merged**
