### PR TITLE
Switch to select on time.After & close channel for track usage

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
@mvdan @vishh

**Comment by mvdan** [comment]
LGTM, nice cleanup!

**Comment by vishh** [comment]
Cc @yujuhong who wanted to not have a select loop :)

**Comment by yujuhong** [comment]
> Cc @yujuhong who wanted to not have a select loop :)

Uh..I meant your original code didn't *need* the redundant select loop. Using select with time.After looks good to me. Thanks for the cleanup.

**Comment by mvdan** [comment]
Looks like jenkins needs godep.

**Pull request merged**
