### PR TITLE
Add Docker's hostname as one of the cAdvisor aliases for the container

### PR DESCRIPTION
**Pull request by hinesmr**
What's the "right" way to take metadata from "docker inspect" and put it into cAdvisor?

We really need the hostname to help identify the statistics provided by Cadvisor. This 1-line patch fixes the problem.

### CODE REVIEW

**Comment by vmarmol** [comment]
Any updates on this? :) Were you able to reuse Docker's name field as an identifier?

**Comment by hinesmr** [comment]
No, that's not possible - it's already used by our management software stack for other purposes. And it's made worse by the fact that Docker does not (yet) support arbitrary key/name value pairs upon creating new containers, so there's no way to store additional metadata inside Docker to be consumed later.

**Comment by emmanuel** [comment]
@hinesmr gliderlabs/registrator reads environment variables from (other) containers as a form of arbitrary metadata. Metadata in that form is not necessarily easily accessible (depending on how you want to access it), but the approach might be worth a look.

**Comment by hinesmr** [comment]
Very interesting. How do you install those environment variables on a per-container basis? Not through libcontainer or docker? Do you install them before the container starts or somewhere in the container filesystem? (I would like to avoid reaching into the container filesystem if at all possible).

**Comment by timstclair** [comment]
This PR looks abandoned. Please reopen it if that's not the case.

**Pull request closed without merging**
