### PR TITLE
Use watch instead of sh.

### PR DESCRIPTION
**Pull request by vmarmol**
Use of sh was making the test flaky and harder to read.

@AnanyaKumar @anushree-n could one of you take a look when you have time? This fixes the integration test.

### CODE REVIEW

**Comment by vmarmol** [comment]
Failure is due to a different, but known flake. *sigh* I'd say to ignore it for now, but we should still get this PR in.

**Comment by vmarmol** [comment]
We're now skipping the known flake. PATL @anushree-n

We don't have to wait for Travis as it runs the same things Jenkins already did.

**Comment by anushree-n** [comment]
Looks good! Thanks!

**Comment by AnanyaKumar** [comment]
Sorry I didn't comment on this - I was trying to figure the code out, and understand what the test was doing, but looks like Anushree got to it first! 

What happens if the first wget is executed after the asserts in lines 264 to 270? Would the test fail because the busy box container hasn't yet sent a packet? (Sorry I probably missed something)

**Comment by vmarmol** [comment]
@AnanyaKumar yes it will most likely miss a packet and the test will fail. It is a flaky test unfortunately...

In practice it doesn't happen often. We need to fix most of the tests in this fixture for cases like this.

**Comment by AnanyaKumar** [comment]
Thanks for the clarification - besides that it looked fine to me :)

**Pull request merged**
