### PR TITLE
statsd docs (Issue #2002)

### PR DESCRIPTION
**Pull request by salaxander**
This is the start of documentation for statsd (issue #2002). Happy to add more detail if needed, but this should be enough to get people off the ground with it :)

### CODE REVIEW

**Comment by salaxander** [comment]
Signed the CLA!

**Comment by salaxander** [comment]
Comment for another CLA check!

**Comment by dashpole** [comment]
make sure you follow this: https://help.github.com/articles/setting-your-commit-email-address-on-github/. From the fact that I dont see your icon on the commits above, this is probably what you are missing

**Comment by salaxander** [comment]
Comment for another CLA check!

**Comment by salaxander** [comment]
@dashpole - Thanks for the guidance on that! Turns out I was missing an alternate email on my Google and GitHub account

**Pull request merged**
