### PR TITLE
New version 0.17.0

### PR DESCRIPTION
**Pull request by rjnagal**

### CODE REVIEW

**Comment by rjnagal** [comment]
@vishh

**Comment by rjnagal** [comment]
Will add the tag once this is merged.

**Comment by vishh** [comment]
LGTM. Instead of a tag, can we create a release branch on HEAD to manage patch releases?

**Comment by rjnagal** [comment]
We never patch branches anyway. It seems like an overkill. I'd expect packaging managers to keep branches of their official releases.

**Pull request merged**
