### PR TITLE
Added possibility to not ignore NumStats field in ContainerInfoRequest

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
cc @dchen1107 @fgrzadkowski @jszczepkowski @mwielgus @vishh

**Comment by jimmidyson** [comment]
Can you describe the use case please?

**Comment by jimmidyson** [comment]
Shouldn't we just respect max results if it's specified?

**Comment by timstclair** [comment]
> Shouldn't we just respect max results if it's specified?

+1 - I think we should just remove the logic that ignores NumStats when a time range is specified.

**Comment by piosz** [comment]
Yes, that would be easier but we have already defined semantic of the request (see [container.go](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L96)) and this would be a breaking change. @rjnagal @vishh @vmarmol any thoughts?

Since we are downsampling the stats to exactly one in [Heapster](https://github.com/kubernetes/heapster/blob/master/sources/datasource/kubelet.go#L69) we can do it on cadvisor side and reduce the network traffic.

**Comment by vishh** [comment]
In a given time range, if NumStats is specified, which samples should be returned? Should it be the oldest or the most recent?

**Comment by piosz** [comment]
The most recent one.

**Comment by vishh** [comment]
That change SGTM. We can perhaps send out an announcement on
`google-containers@` regarding this API change.

**Comment by jimmidyson** [comment]
Definitely most recent samples.

I'm happy with the breaking change. cadvisor is still only a 0.x release so API stability not guaranteed :stuck_out_tongue_closed_eyes:

**Comment by piosz** [comment]
cadvisorJenkinsBot writing comments... sounds interesting ;)

**Comment by piosz** [comment]
Changed the code to make a breaking change.

**Comment by jimmidyson** [comment]
@cadvisorJenkinsBot has become sentient!

**Comment by vishh** [comment]
ok to test

**Comment by rjnagal** [comment]
That was me reply through mail and expecting github to do the right thing. I can be easily mistaken for a bot though :(

**Comment by vishh** [comment]
add to whitelist

**Comment by piosz** [comment]
@rjnagal @vishh could you please grant LGTM to the PR?

The integration test is broken:
```
Error 0: failed to make remote testing directory: command "gcloud" ["compute" "ssh" "--zone" "us-central1-f" "cadvisor-ubuntu-trusty" "--" "mkdir" "-p" "/tmp/cadvisor-5471"] failed with error: exit status 1 and output: "ERROR: (gcloud.compute.ssh) The required property [project] is not currently set.\nYou may set it for your current workspace by running:\n\n  $ gcloud config set project VALUE\n\nor it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]\n"
Build step 'Execute shell' marked build as failure
```

**Comment by jimmidyson** [comment]
That's normally a transient error - let's try retesting...

**Comment by jimmidyson** [comment]
retest this please

**Comment by piosz** [comment]
thanks @jimmidyson

**Comment by jimmidyson** [comment]
I haven't looked (lazy!) but are we defaulting max stats to -1 somewhere?

**Comment by piosz** [comment]
According to the documentation the default is 60 (see https://github.com/google/cadvisor/blob/master/info/v1/container.go#L95).

**Comment by jimmidyson** [comment]
The failure is unrelated... Jenkins seems to get like this sometimes.

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
Why 60? Assume that means 1 minute of stats but seems a strange default when housekeeping time is configurable.

But we can discuss that in a different PR. IMO -1 should be the default if unspecified.

**Comment by piosz** [comment]
create an issue #1011 for this purpose

**Comment by jimmidyson** [comment]
Anyway LGTM

**Comment by jimmidyson** [comment]
Unit tests run fine for me locally so happy to merge.

**Comment by piosz** [comment]
Thanks @jimmidyson. What is the release process of cadvisor?

**Comment by jimmidyson** [comment]
Are you looking to get this into kubernetes ASAP? I have a PR to bump cadvisor so I can tag it here & include this bump in that PR if you'd like?

**Comment by piosz** [comment]
Yes, please. Thank you very much in advance.

**Comment by vishh** [comment]
Piotr, can you send out an announcement about this API change to
google-containers@ ?

**Pull request merged**
