### PR TITLE
Added findutils at the Dockerfile

### PR DESCRIPTION
**Pull request by lborguetti**
Guys,

This PR fix this issue: https://github.com/google/cadvisor/issues/1641

Thanks!

### CODE REVIEW

**Comment by jharshman** [comment]
Would be awesome to have this fix merged in.  The related error in issue #1641 is an annoyance.

**Comment by lborguetti** [comment]
Merged with master to fix cAdvisor builds!

**Comment by dashpole** [comment]
it looks like your account isnt associated with the commits.  You will need to make sure those are consistent, and then squash.

**Comment by jharshman** [comment]
@dashpole #1712

**Comment by lborguetti** [comment]
@dashpole Sorry about the delay. Its done. 

Thanks.

**Pull request merged**
