### PR TITLE
Updating inotify to fix memory leak

### PR DESCRIPTION
**Pull request by krousey**
Picking up a fix I made in https://go-review.googlesource.com/#/c/24289/

#1339

### CODE REVIEW

**Comment by krousey** [comment]
cc @dchen1107

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
LGTM

**Comment by yujuhong** [comment]
ok to test

**Comment by yujuhong** [comment]
Not sure if I am in the admin list :-\ 

/cc @vishh @timstclair

**Comment by jimmidyson** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
@jimmidyson thanks! Maybe the bot wasn't running at the time.

**Comment by timstclair** [comment]
@krousey we're going to do another cAdvisor update, and it would be good to include this. Could you send a cherrypick against the v0.23 branch?

**Comment by krousey** [comment]
@timstclair What is the cherrypick process for this repo?

**Comment by timstclair** [comment]
Cherrypick your commit into a local copy of the v0.23 branch (via `git cherry-pick`), then submit a PR from your branch to the v0.23 branch. Ping me if you run into trouble or want a more detailed explanation.

**Pull request merged**
