### PR TITLE
Drop dependency on operatingsytem package in docker/docker

### PR DESCRIPTION
**Pull request by dims**
Avoid dependency on docker/docker

### CODE REVIEW

**Comment by dims** [comment]
cc @mattjmcnaughton

**Comment by mattjmcnaughton** [comment]
Exciting!

**Comment by dashpole** [comment]
looks like this is more than just a straight copy from docker/docker, and handles some additional cases, such as darwin, etc.  Can you update the description with the improvements you made?

**Comment by dims** [comment]
@dashpole it's a re-implementation as i did not want to do a straight copy, it covers the same platforms as the docker/docker one. will write some notes below:

- `getOperatingSystem` is a private method, so we are not exposing this to the world
- operatingsystem_unix.go is for all the unix os(es)
- darwin and freebsd do not support files for looking up the release, so run `uname` (same command as used in the docker package)
- on the other unixes, we look for 2 files one after another (similar to the stuff in docker), but we do not use shellwords to parse, we just use a regexp to find the key with `PRETTY_NAME` instead of reading line by line
- for windows, we use the code from winstats, but make sure we mint the same version string as the docker/docker one used to.

**Pull request merged**
