### PR TITLE
Stop using the global prometheus registry

### LINKED ISSUE #1459: Remove usage of package prometheus globals
cAdvisor is often used as library and embedded into other programs, its usage of package globals makes isolation impossible can be even harmful. The usage of package `http` has already been removed, package `flag` globals are tracked in #1175 which leaves us with package `prometheus` globals. Using a separate registry will ensure that cAdvsior controlled metrics won't leak.

### PR DESCRIPTION
**Pull request by grobie**
Replace usage of the global Prometheus registry with a private registry
object which will be exported under the given prometheus path.

Fixes #1459.

### CODE REVIEW

**Comment by grobie** [comment]
This removes the http_* metrics. The instrument handler is deprecated as it needs to be rewritten. Not sure you would like to keep them?

**Comment by grobie** [comment]
Depending on the outcome of the discussion in kubernetes/kubernetes#32638 we'll need to change the integration of cAdvsior in the kubelet once this PR is merged. We probably could also just stop using `RegisterPrometheusHandler` in the kubernetes code base to avoid the usage of the global registry.

**Comment by jimmidyson** [comment]
:+1:

I don't mind the loss of http_* metrics.

**Comment by jimmidyson** [comment]
@grobie Needs a rebase please.

**Comment by grobie** [comment]
@jimmidyson done

**Comment by cmluciano** [comment]
Is this awaiting a maintainer review?

**Comment by grobie** [comment]
Anything left for me to do here? If you're not going to accept this, I can also just close it. @jimmidyson @dashpole

**Comment by dashpole** [comment]
`W0416 16:16:43.668] vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:75: undefined: prometheus.DefaultGatherer`
`W0416 16:16:43.668] vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:80: undefined: prometheus.Gatherer`
Looks like it doesnt compile?

**Comment by cmluciano** [comment]
Might be related https://github.com/prometheus/client_golang/commit/f0c45acc506afde8b240d7d377f61845ba3089e3 ?

**Comment by grobie** [comment]
I'm sorry for the noise @dashpole. I updated the dependencies (which will bring several improvements to the metrics exported by Prometheus) and that fixed the build.

**Comment by dashpole** [comment]
sorry, this fell off of my radar.
please rebase and squash

**Comment by grobie** [comment]
@dashpole you sure you want me to squash these two commits together? I'm not sure I see the point, they are independent changes which can be applied in isolation. Given the massive diff caused by vendor updates, I understood it to be best practice to separate them from actual code changes.

**Comment by dashpole** [comment]
usually, we just squash to make the git tree more readable, but I see your point.  We can merge this as is once tests pass.

**Comment by grobie** [comment]
@dashpole another week of ping pong ;-)

**Comment by dashpole** [comment]
Ill see if I can get the test infra stuff fixed today.  Then we can merge this.

**Comment by Random-Liu** [comment]
Verified that this PR causes https://github.com/google/cadvisor/issues/1671 and https://github.com/kubernetes/kubernetes/issues/47744.

It seems that Prometheus v0.8.0 added some consistency check https://github.com/prometheus/client_golang/pull/214, which breaks the metrics.

Filed https://github.com/google/cadvisor/pull/1679 to work around this for now. We should figure out and fix the inconsistent metrics in the future.

**Pull request merged**
