### PR TITLE
goauth2 replacement

### PR DESCRIPTION
**Pull request by kargakis**
I am not sure if the way I set up the token is right since I am not very familiar with authentication stuff. Please review the change and let me know what needs to change.

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vmarmol** [comment]
Looks like we don't ever get the token.

**Comment by kargakis** [comment]
> Looks like we don't ever get the token.

I changed the generation of the token to be handled from `jwt` as it was before. Can you retest this?

**Comment by vmarmol** [comment]
Thanks @kargakis! This looks good. @rjnagal is there any other testing you'd like to do?

**Comment by rjnagal** [comment]
Let me bring up an instance while travis is still working on it.

**Comment by vmarmol** [comment]
@kargakis looks like something is missing from the deps.

**Comment by rjnagal** [comment]
Hit the same error as travis. @kargakis Can you run `godep save ./...`

**Comment by kargakis** [comment]
Missing deps added and Travis is happy

**Comment by rjnagal** [comment]
testing locally now

**Comment by rjnagal** [comment]
LGTM.

Works great. Thanks @kargakis

**Pull request merged**
