### PR TITLE
[docker] add overlay2 storage driver

### PR DESCRIPTION
**Pull request by bamarni**
Signed-off-by: Bilal Amarni <bilal.amarni@gmail.com>

### CODE REVIEW

**Comment by dchen1107** [comment]
@bamarni, can we have some cadvisor tests for validating overlay2 driver? Some basic sanity check tests here?

**Comment by dchen1107** [comment]
The code is pretty clean and lgtm.

**Comment by bamarni** [comment]
@dchen1107 : I've added a test. Integration test support for overlay2 is also ready, however I think it'd require a machine running docker with overlay2 during CI? I'm not sure how to set this up.

**Comment by bamarni** [comment]
@dchen1107 : should I resolve conflicts and squash? Please let me know if anything else is missing for that PR.

**Comment by dashpole** [comment]
@k8s-bot test this

**Comment by dashpole** [comment]
yes, please rebase and squash.  Code changes lgtm as well.  Have you manually tested this at all?  I dont think adding a full test suite should block this, but I would at least like to know that someone has successfully used it.

**Comment by bamarni** [comment]
@dashpole : yes I had checked on the web interface, there were a place showing disk usage with a red bar. It wasn't displayed at all before my changes and displayed properly after, so it seemed fine to me, is there anything else to be careful about?

I don't have a setup at the moment to check it again now that I've rebased, but it was trivial conflicts.

**Comment by bamarni** [comment]
I've rebased and tested it again with docker and overlay2, cf. below some screenshots from the container overview page on the web interface : 

before :
cadvisor_before

after : 
cadvisor_after

**Comment by dashpole** [comment]
@k8s-bot test this

**Comment by dashpole** [comment]
k8s-bot ok to test

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Pull request merged**
