### PR TITLE
alpine linux thin-provisioning-tools thin_ls location

### PR DESCRIPTION
**Pull request by zaquestion**
https://pkgs.alpinelinux.org/package/edge/testing/x86_64/thin-provisioning-tools install thin_ls in /sbin/

bash-4.3# which thin_ls
/sbin/thin_ls

### CODE REVIEW

**Comment by zaquestion** [comment]
I signed it!

**Comment by dashpole** [comment]
assigning to @derekwaynecarr since this is DM related

**Comment by derekwaynecarr** [comment]
LGTM, but be aware that we have found performance issues with thin_ls

**Comment by derekwaynecarr** [comment]
can you rebase?

**Comment by zaquestion** [comment]
Change was introduced here: https://github.com/google/cadvisor/commit/cd41c0bd603392da535c529fe55757b9e09c98b3

**Pull request closed without merging**
