### PR TITLE
Fixed missing white listed env labels(#2327)

### PR DESCRIPTION
**Pull request by Colstuwjx**

### CODE REVIEW

**Comment by dashpole** [comment]
The only problem is that this is a change in behavior for non-docker runtimes, since they will now get env vars added to their metrics.  Can we also introduce a `env_metadata_whitelist` flag that isn't docker-specific and deprecate the docker-specific one?

**Comment by alyssahardy** [comment]
Are there any plans to fix this bug anytime soon?

**Comment by Colstuwjx** [comment]
> Are there any plans to fix this bug anytime soon?
 
@alyssahardy I have no time to work on this PR anymore, feel free to continue this job :)

**Comment by bobbypage** [comment]
I'm going to close this for now since there isn't any update, please re-open if appropriate.

**Pull request closed without merging**
