### PR TITLE
riemann support

### PR DESCRIPTION
**Pull request by konukhov**
Hi there,

It would be great if cadvisor could be able to send metrics directly to [Riemann](http://riemann.io) – here's my implementation.

### CODE REVIEW

**Comment by rjnagal** [comment]
Thanks for the patch @konukhov 

Can you run gofmt on the changes and add a doc on setting up cadvisor+reimman?

**Comment by konukhov** [comment]
Hi @rjnagal

Thanks for the fast feedback! 

I just pushed updated documentation + gofmt'd my code. I also added some TCP connection recovery logic to the Riemann client in order to make events delivery more reliable.

**Comment by rjnagal** [comment]
Thanks for the changes, @konukhov .

Just an update: Most of us are busy with dockercon this week. I'll probably get to the review by end of week. I also want to try bringing up Reimann and cadvisor as containers together for quick verification. If you have a dockerfile or compose config to test them together, please drop it here too.

**Comment by konukhov** [comment]
Thanks for the update, @rjnagal!

I'm quite busy this week too, so I'll try to provide containers/configs for testing by the end of this week.

**Comment by szubster** [comment]
Any news on this?

**Comment by konukhov** [comment]
@szubster Hi!

Sorry I've been quite busy lately, so I haven't got time to fix/provide things @rjnagal asked for. I'll try to finish this in a week or so.

**Comment by selvik** [comment]
@konukhov Thanks for working on this. Looking forward to trying this out when it's in.

**Comment by edannenberg** [comment]
:+1:

**Comment by jfoy** [comment]
FYI https://github.com/kubernetes/heapster/pull/379

**Comment by edannenberg** [comment]
If this is on hold because of a missing test setup via docker-compose I can put something together. Would really like to see this merged.

**Comment by timstclair** [comment]
This PR has been labeled **inactive** due to lack of recent activity. If it remains in this state for more than 2 weeks, it will be closed. If it is still being developed, please provide a status update.

**Comment by timstclair** [comment]
Closing as **inactive**. Please reopen if development resumes.

**Pull request closed without merging**
