### PR TITLE
Handle initial zero value of lastError.

### PR DESCRIPTION
**Pull request by vmarmol**
Also reduce logging to once every minute.

### CODE REVIEW

**Comment by vmarmol** [comment]
Ping @rjnagal this didn't let us log anything since the initial value was always zero.

**Comment by vmarmol** [comment]
Open to discussion on whether a minute or more/less often. An hour seemed way too long :)

**Comment by vishh** [comment]
LGTM

**Comment by rjnagal** [comment]
doh. One minute is fine for now.

**Pull request merged**
