### PR TITLE
chore: add storage_driver_buffer_duration in Influxdb storage docs

### PR DESCRIPTION
**Pull request by matcornic**

### CODE REVIEW

**Comment by matcornic** [comment]
I signed it!

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by dashpole** [comment]
@k8s-bot test this

**Comment by dashpole** [comment]
I would prefer if you used the same description as in storage/common_flags.go, just to be consistent.  This will have to rebase before it can go in.

**Comment by dashpole** [comment]
please squash, and we can get this merged!

**Pull request merged**
