### PR TITLE
Backporting #2868 on release v0.39.x

### PR DESCRIPTION
**Pull request by daniellavoie**
Backporting:
* #2868

### CODE REVIEW

**Comment by daniellavoie** [comment]
Hello @iwankgb @bobbypage, sorry to ping you directly. Could you help out identifying someone who can review this backport. The sig-node team agreed to bump kubernetes with a new hot fix when backport is available. 

Thank you!

**Comment by bobbypage** [comment]
LGTM, thanks for backporting this.

**Comment by daniellavoie** [comment]
Thank you! Could you point out to some info regarding the process to cut a new 0.39.x release?

**Comment by bobbypage** [comment]
https://github.com/google/cadvisor/blob/master/docs/development/releasing.md describes how to cut cAdvisor releases. This is something that cAdvisor maintainers need to do. I will cut a new release for v0.39 which includes the fix.

**Comment by bobbypage** [comment]
pushed https://github.com/google/cadvisor/releases/tag/v0.39.3

**Pull request merged**
