### PR TITLE
Return all stats by default.

### PR DESCRIPTION
**Pull request by vmarmol**
Rather than relying on 64 being a "big enough" value.

### CODE REVIEW

**Comment by vishh** [comment]
Curious: How does this change help deal with the kubelet part of the issue?

**Comment by vishh** [comment]
LGTM

**Comment by rjnagal** [comment]
Returning all stats doesn't seem like a good default, as it can change based on our memory storage/backend setup.

Does it fix a real problem?

**Comment by vmarmol** [comment]
No, it just fixed an expected behavior (in my opinion). I'm fine leaving a default but having it documented. It is better than returning all...will change this PR for that.

@vishh, not for that but there is a followup with your name on it :)

**Comment by vishh** [comment]
We should separate time range queries from the number of stats. Requiring a max number of stats for time range queries is non intuitive personally.

**Comment by vmarmol** [comment]
@vishh I can see the usecase where someone wants to get the 10 stats before a certain time or limit the number of results. But it does feel like a better default for time-based queries is "all" rather than an arbitrary limit. That was the logic behind this PR. It would be simpler if we returned "all" by default in our cases. WDYT @rjnagal? It may be specific to the flags on the memory storage, but it'll provide consistent behavior.

An alternative is to say that the default when specifying both start and end is "all" unless otherwise specified.

**Comment by rjnagal** [comment]
Separating out time and count queries sounds fine. Not receiving a ton of
stats by default would be nice. When we are using an external storage, will
it try to get all stats from backend?

**Comment by vmarmol** [comment]
We no longer fetch stats from external drivers. We just use them for export.

I'm fine with specifying: default NumStats = 60 and if Start and End are specified NumSats is ignored.

**Comment by rjnagal** [comment]
SG.

**Comment by vmarmol** [comment]
Updated to document the limit, set the default, and ignore NumStats for time range queries. PTAL @vishh @rjnagal

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
