### PR TITLE
Lazily init DBus only when it is needed

### PR DESCRIPTION
**Pull request by smarterclayton**
OpenShift has some cAdvisor packages in its import chain. The init() here
invokes Dbus start even when cAdvisor is not actively running or being
used (in our packages).  This change makes the systemd check and dbus
initialization and connection lazy, occuring only the first time someone
invokes UseSystemd().

Seemed like the simplest possible tweak.

### CODE REVIEW

**Comment by smarterclayton** [comment]
I have a CLA under Red Hat.

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
LGTM, will wait for green. Thanks @smarterclayton

**Comment by smarterclayton** [comment]
Thank you - cAdvisor gives me such pretty numbers to show everyone.  :)

----- Original Message -----

**Comment by vishh** [comment]
Tests are passing. Merging this PR.

**Pull request merged**
