### PR TITLE
Add Elasticsearch 5.x storage support

### PR DESCRIPTION
**Pull request by oopschen**
Add Elasticsearch 5.x storage support.
Enhance  date format for index name resolvition.
Enhance client options.

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by dashpole** [comment]
@timstclair this looks like an entirely new storage driver.  Is it not possible just to update the old ES driver?  If it is a new one, this is probably blocked on #1458...

**Comment by dashpole** [comment]
@k8s-bot test this

**Comment by dashpole** [comment]
@oopschen apologies for the delay.  Is it possible to update the existing ES storage driver rather than adding a new one while maintaining compatibility with older versions?  I don't think we should have a driver for each version of each driver if we can avoid it.

**Comment by oopschen** [comment]
@dashpole  There is two major release of elasticsearch: 2.x and 5.x, and there are not compatible. I think it is better to support two of them to offer a better user experience for developers.

It definitely possible to merge two major release ES storage, if it is required, should i open a new pull request or merge them in this pull request?

**Comment by dashpole** [comment]
@timstclair should this wait on #1458?

**Comment by timstclair** [comment]
It depends on whether it would be an update to the existing elasticsearch
plugin, or a new one. I was blocking new plugins, but not changes to
existing ones.

**Comment by dashpole** [comment]
It is a new plugin, since elasticsearch 2.x and 5.x are not compatible

**Comment by rikatz** [comment]
Since the drivers from 2 and 5 aren't compatible, we need to have 2 drivers :(

I've faced this very same issue in Heapster.

There are some prettier solutions here (maybe using an interface, configuring the version in storage URI when starting cAdvisor), but the point here is that we still need 2 drivers :)


Haven't tested this implementation by itself. I've missed an _test file.

About the refactor of cAdvisor storage (as in #1458), can't say something about this (as I'm no expert in developing) but sounds better to me anyway to have plugable storage instead of maintaining each solution market. By the way, would prometheus be a 'storage' implementation, or should we keep this separate as a '/metric' implementation? :)

**Comment by jjduhamel** [comment]
Any update on this?  Would be good to add support for this asap.

**Comment by jindov** [comment]
Waiting for this support, I use ELK 5.5 stack on system

**Comment by mostolog** [comment]
Already added +1.

Having this blocked by #1458 for so long doesn't make any sense to me.

Adding this driver as "elasticsearch5" while the other is still mantained as "elasticsearch" would do the trick.

**Comment by liangyuanpeng** [comment]
any update? 

 maybe current the es version supported is too low, we should update version of es for stoarge :cry:

**Comment by bobbypage** [comment]
I agree with the direction in https://github.com/google/cadvisor/issues/1458#issuecomment-691166958 we want to avoid adding new storage drivers in cAdvisor and instead rely on prometheus metrics + external backends that can ingest those metrics. As a result, closing this PR for now.

**Pull request closed without merging**
