### PR TITLE
Start Manager v2 API

### PR DESCRIPTION
**Pull request by timstclair**
Reorganize some manager V2 APIs & add a V2 ContainerInfo (and method for retrieving it).

This PR looks a lot bigger than it actually is. Most of the changes are just moves. New code includes:

- V2 ContainerInfo API
- V2 GetContainerInfo
- manager_v2.go (and corresponding test) to separate V2 APIs from V1 APIs. The V2 APIs are exported by the  V2() method on `Manager`, but the `v2Manager` is intentionally not exported.
- test for ConvertStats (which caught a bug: `Labels` were not converted)

This change is a prerequisite for https://github.com/kubernetes/kubernetes/issues/12483

### CODE REVIEW

**Comment by timstclair** [comment]
cc/ @vishh @dchen1107

**Comment by vishh** [comment]
ok to test

**Comment by timstclair** [comment]
Friendly ping? Is anything blocking this? Are we just waiting for the k8s API to get finalized?

(@vishh I can't assign cadvisor PRs)

**Comment by jimmidyson** [comment]
@timstclair Yes we're waiting on the kubernetes API PR so we make sure we're compatible. I know that's a bit backwards but once we start the v2 API here we'll find it harder to break compatibility.

**Comment by timstclair** [comment]
ok to test

**Comment by jimmidyson** [comment]
Needs rebasing...

**Comment by timstclair** [comment]
I'm closing this for now, in favor of the simplified https://github.com/google/cadvisor/pull/1045

**Pull request closed without merging**
