### PR TITLE
Process BTRFS and whole-disk filesystem stats

### PR DESCRIPTION
**Pull request by arkadijs**
XFS users might complain, but we - Docker users - use BTRFS. :)
Typical usage of CoreOS (on AWS) is to format whole device to BTRFS and mount it on /var/lib/docker, thus whole-disk stats must also be collected.

### CODE REVIEW

**Comment by vishh** [comment]
"TestGetDiskStatsMap" unit test is failing. Can you address the issue?

**Comment by arkadijs** [comment]
Sorry for that, fixed.
I can force-push as a single commit if necessary.

**Comment by vmarmol** [comment]
LGTM, yes please. One commit would be nice :)

**Comment by arkadijs** [comment]
Also added device-mapper to regex. Works for BTRFS volumes on LVM as they appears as /dev/dm-* in /proc/mounts even if mounted as /dev/vg/lv.
Not a complete solution because ext4 on LVM appears as intended, ie. /dev/vg/lv and thus does not match /proc/diskstats. No idea why such difference.

**Comment by arkadijs** [comment]
I checked it on Docker host running with devicemapper storage driver. It doesn't help to collect the stats, but not making this worse either:

    {
      "device": "/dev/mapper/docker-202:1-922914-e6128e016bdac12e73c36d70659e4984159878c3c33e1e3b962891185aaeb525",
      "capacity": 10434662400,
      "usage": 651108352,
      "reads_completed": 0,
      "reads_merged": 0,
      "sectors_read": 0,
      "read_time": 0,
      "writes_completed": 0,
      "writes_merged": 0,
      "sectors_written": 0,
      "write_time": 0,
      "io_in_progress": 0,
      "io_time": 0,
      "weighted_io_time": 0
    },

**Comment by vishh** [comment]
LGTM. @vmarmol any other comments?

**Comment by vmarmol** [comment]
LGTM

**Pull request merged**
