### PR TITLE
Fix #2566 warning instead of error when core_id or physical_package_id not available

### LINKED ISSUE #2566: Wrong CPU count on x86_64
It is still an issue, apparently: https://github.com/kubernetes/kubernetes/issues/89859

CC: @katarzyna-z

### PR DESCRIPTION
**Pull request by katarzyna-z**
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>

### CODE REVIEW

**Comment by katarzyna-z** [comment]
@BenTheElder Could you verify if cAdvisor from this pull request correctly reports cpus?

**Comment by katarzyna-z** [comment]
I see that for some cpus topology directory is missing, cAdvisor reads "core_id" and "physical_package_id" from topology directory. I need to extend this pull request to handle the case for "physical_package_id"

**Comment by iwankgb** [comment]
It's a bit surprising: it should be there by default. https://elixir.bootlin.com/linux/latest/source/drivers/base/topology.c

**Comment by katarzyna-z** [comment]
> It's a bit surprising: it should be there by default. https://elixir.bootlin.com/linux/latest/source/drivers/base/topology.c

but in [provided ls outputs](https://github.com/kubernetes/kubernetes/issues/89859#issuecomment-637105431) event topology directory is sometimes missing...
```
$ ls /sys/devices/system/node/node0/cpu0
cache  cpufreq  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  microcode  node0  power  subsystem  thermal_throttle  topology  uevent

$ ls /sys/devices/system/node/node0/cpu10
cpufreq  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  online  power  subsystem  uevent

$ ls /sys/devices/system/node/node0/cpu8
cpufreq  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  online  power  subsystem  uevent
```

**Comment by katarzyna-z** [comment]
@BenTheElder @uablrek Could you verify if this works in your environment?

**Comment by BenTheElder** [comment]
> E0604 21:06:19.576087 2059821 info.go:109] Failed to get topology information: Unable to read core id for processor 10 from processor	: 0

excerpt from `curl http://localhost:8080/api/v2.0/machine`:

`"num_cores":0,"num_physical_cores":6,"num_sockets":1`

**Comment by katarzyna-z** [comment]
@BenTheElder @dghubble I've changed the pull request. Could you verify if this pull request fixes your issue?

**Comment by katarzyna-z** [comment]
fyi, in next week I'll have limited access to my computer so it'll be difficult for me to help with this issue but since 15th June I can try to help

**Comment by dghubble** [comment]
I see `"num_cores": 2, "num_physical_cores": 1, "num_sockets": 1` with cadvisor cff7e58 https://github.com/kubernetes/kubernetes/issues/91795#issuecomment-639768345 (on my OS, SMT is disabled so I think the num_cores used to be 1 in prior versions).

**Comment by BenTheElder** [comment]
```
[bentheelder@bentheelder:~/go/src/github.com/google/cadvisor·2020-06-05T13:19:30-0700·pr2567@cff7e58e]
$ sudo ./cadvisor
[sudo] password for bentheelder: 
W0605 13:19:39.462555 2201278 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu10, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu10/topology/core_id: no such file or directory
W0605 13:19:39.462669 2201278 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu11, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu11/topology/core_id: no such file or directory
W0605 13:19:39.463068 2201278 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu6, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu6/topology/core_id: no such file or directory
W0605 13:19:39.463103 2201278 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu7, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu7/topology/core_id: no such file or directory
W0605 13:19:39.463132 2201278 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu8, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu8/topology/core_id: no such file or directory
W0605 13:19:39.463162 2201278 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu9, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu9/topology/core_id: no such file or directory
```

`"num_cores":12,"num_physical_cores":6,"num_sockets":1`

I'm pretty sure SMT / hyperthreading is disabled on this machine, 12 cores seems incorrect given that half of them are offline:
```
$ lscpu -e -a
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE    MAXMHZ    MINMHZ
  0    0      0    0 0:0:0:0          yes 4000.0000 1200.0000
  1    0      0    1 1:1:1:0          yes 4000.0000 1200.0000
  2    0      0    2 2:2:2:0          yes 4000.0000 1200.0000
  3    0      0    3 3:3:3:0          yes 4000.0000 1200.0000
  4    0      0    4 4:4:4:0          yes 4000.0000 1200.0000
  5    0      0    5 5:5:5:0          yes 4000.0000 1200.0000
  6    -      -    - :::               no 4000.0000 1200.0000
  7    -      -    - :::               no 4000.0000 1200.0000
  8    -      -    - :::               no 4000.0000 1200.0000
  9    -      -    - :::               no 4000.0000 1200.0000
 10    -      -    - :::               no 4000.0000 1200.0000
 11    -      -    - :::               no 4000.0000 1200.0000
```

**Comment by iwankgb** [comment]
As far as I can remember historically cAdvisor was ignoring CPU online/offline information. I guess that after changes taking topology into consideration were developed online/offline status must be taken into consideration.

**Comment by iwankgb** [comment]
And it seems to be pretty correct assumption:
```
[root@ams1-c1 cpu7]# cat online
1
[root@ams1-c1 cpu7]# echo off > /sys/devices/system/cpu/smt/control
[root@ams1-c1 cpu7]# pwd
/sys/devices/system/node/node0/cpu7
[root@ams1-c1 cpu7]# cat online
0
[root@ams1-c1 cpu7]# echo on > /sys/devices/system/cpu/smt/control
[root@ams1-c1 cpu7]# cat online
1
```
`lscpu` output seems to be consistent with what @BenTheElder provided:
```
[root@ams1-c1 cpu7]# echo off > /sys/devices/system/cpu/smt/control
[root@ams1-c1 cpu7]# lscpu -e -a
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE MAXMHZ    MINMHZ
0   0    0      0    0:0:0:0       yes    4100.0000 800.0000
1   0    0      1    1:1:1:0       yes    4100.0000 800.0000
2   0    0      2    2:2:2:0       yes    4100.0000 800.0000
3   0    0      3    3:3:3:0       yes    4100.0000 800.0000
4   -    -      -    :::           no     4100.0000 800.0000
5   -    -      -    :::           no     4100.0000 800.0000
6   -    -      -    :::           no     4100.0000 800.0000
7   -    -      -    :::           no     4100.0000 800.0000
```
@dashpole, I think that cAdvisor must start taking cpu hotplug status into consideration now.

**Comment by iwankgb** [comment]
@katarzyna-z I think that adding something like `IsCPUOnline()` function to `sysfs.SysFs` could help a lot. It should be used to determine whether any further processing for given CPU should follow.
I can confirm that I'm getting the very same error messages:
```W0606 20:02:05.262727   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu4, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu4/topology/core_id: no such file or directory
W0606 20:02:05.262750   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu5, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu5/topology/core_id: no such file or directory
W0606 20:02:05.262762   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu6, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu6/topology/core_id: no such file or directory
W0606 20:02:05.262774   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu7, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu7/topology/core_id: no such file or directory
```

**Comment by katarzyna-z** [comment]
> @katarzyna-z I think that adding something like `IsCPUOnline()` function to `sysfs.SysFs` could help a lot. It should be used to determine whether any further processing for given CPU should follow. And if the CPU should increase any resource counter.
> I can confirm that I'm getting the very same error messages:
> 
> ```
> W0606 20:02:05.262750   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu5, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu5/topology/core_id: no such file or directory
> W0606 20:02:05.262762   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu6, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu6/topology/core_id: no such file or directory
> W0606 20:02:05.262774   15794 sysinfo.go:390] Cannot read core id for /sys/devices/system/node/node0/cpu7, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu7/topology/core_id: no such file or directory
> ```

@iwankgb Great idea!

@dashpole I'll continue the work on 15th June when I come back from my short vacation.

**Comment by iwankgb** [comment]
@katarzyna-z go back to doing nothing, please ;)

Follow up can be found in #2579.

**Pull request merged**
