### PR TITLE
Add make release target

### PR DESCRIPTION
**Pull request by jimmidyson**
@vishh This means you can just do `make release` & tag will be created & binaries uploaded. Will need to create changelog manually for now, but thinking how we automate that with something like https://github.com/skywinder/github-changelog-generator in future.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Flake...

**Comment by jimmidyson** [comment]
No code changes so self-merging.

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
We usually publish a few checksums for the binary. Some users have explicitly asked for it. Can you update the 0.19.1 release with the checksums?

**Pull request merged**
