### PR TITLE
Create cadvisor client with http client timeout

### PR DESCRIPTION
**Pull request by kitt1987**
A new client builder **NewClientWithTimeout** is added, which can create a HTTP client with timeout instead of http.DefaultClient.

### CODE REVIEW

**Comment by dashpole** [comment]
I am not going to bother testing it right now, as our test infrastructure is having problems.  Ill test when that is fixed.

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by kitt1987** [comment]
Hi, any progress?

**Comment by dashpole** [comment]
please rebase and squash

**Comment by kitt1987** [comment]
I've done that. Thanks.

**Pull request merged**
