### PR TITLE
snap package

### PR DESCRIPTION
**Pull request by mikeroyal**
includes snapcraft.yaml to build snap.

### CODE REVIEW

**Comment by mikeroyal** [comment]
I signed it

**Comment by dashpole** [comment]
/ok-to-test

I am not very familiar with snap.  What does this do?

**Comment by mikeroyal** [comment]
Hi @dashpole, snap is a package format that makes setting up and installing applications, run-times, and services across the Linux Desktop, Server, and IoT based devices easier. Snaps are supported across 41 Linux distributions. https://snapcraft.io/

**Comment by dashpole** [comment]
cool, sounds good to me.  Can you move this into the `/deploy` directory?

**Pull request closed without merging**
