### PR TITLE
updating go-conenctions to v0.4.0

### PR DESCRIPTION
**Pull request by ykakarap**
Updating the "go-connections" version to v0.4.0 from v0.3.0

cc @dims

### CODE REVIEW

**Comment by ykakarap** [comment]
@googlebot I signed it!

**Comment by dashpole** [comment]
Is there a reason for the update?  Can you update the description?

**Comment by dims** [comment]
@dashpole looking at https://github.com/docker/go-connections/compare/v0.3.0...v0.4.0 there are a couple of PRs in there for TLS and cipher updates, So requested @ykakarap to file an update we can then turn around and use in kubernetes/kubernetes.

**Pull request merged**
