### PR TITLE
Rename readInt64 -> readUInt64 for clarity

### PR DESCRIPTION
**Pull request by jimmidyson**
Minor rename for my benefit as I misunderstood the purpose of the function in a review.

### CODE REVIEW

**Comment by timstclair** [comment]
LGTM

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
Same old very annoying flake... must look at it some time.

**Comment by jimmidyson** [comment]
Self-merging after LGTM.

**Pull request merged**
