### PR TITLE
Eliminate race in integration test

### PR DESCRIPTION
**Pull request by vmarmol**
Testing the Jenkins build.

### CODE REVIEW

**Comment by vmarmol** [comment]
@rjnagal this should be ready for review and fix head.

**Comment by vmarmol** [comment]
Integration test is passing: http://104.154.52.74/job/cadvisor-e2e/813/console

**Comment by rjnagal** [comment]
LGTM

**Comment by vmarmol** [comment]
Travis is green and Jenkins passes: http://104.154.52.74/job/cadvisor-e2e/818/console

**Pull request merged**
