### PR TITLE
Add s390x support again 

### PR DESCRIPTION
**Pull request by madeelibm**
thin-provisioning-tools package is now available in Alpine Linux. We have tested and added it in latest, 3.19 and 3.18 releases.

### CODE REVIEW

**Comment by madeelibm** [comment]
Can someone help to merge this PR?

**Comment by mrunalp** [comment]
Looks fine. I have kicked off the tests.

**Comment by rphillips** [comment]
The failed test is a package manager flake.

LGTM as well.

**Review by mrunalp — APPROVED** [review]

**Comment by haircommander** [comment]
@iwankgb @bobbypage PTAL

**Review by iwankgb — APPROVED** [review]

**Comment by iwankgb** [comment]
@madeelibm merge master, please

**Pull request merged**
