### PR TITLE
Use raw as a bases for a rkt container handler

### PR DESCRIPTION
**Pull request by sjpotter**
Mostly the same as raw except for the handling of ListSubcontainers and the creation of an Alias that matches the kubernetes container id.

moved a lot of common functionality to common/ but didn't modify raw yet to use the common stuff.

### CODE REVIEW

**Comment by sjpotter** [comment]
and again, need to figure out why a branch off an up to date master causes other things to be pulled in

**Comment by vishh** [comment]
Hmm. A rebase against master should fix that for now.

**Comment by yifan-gu** [comment]
What's the status on this PR? Can we maybe split it into several PRs for easy reviewing? @sjpotter

**Comment by vishh** [comment]
It will help if we can split this PR into several ones - Create a common package, move docker and raw handlers to use that and then add rkt.

**Comment by sjpotter** [comment]
ok, I'll see what I can do.

**Comment by feiskyer** [comment]
+1 for splitting.

**Comment by sjpotter** [comment]
this was supreseded by merged PRs https://github.com/google/cadvisor/pull/1128 and https://github.com/google/cadvisor/pull/1154

**Pull request closed without merging**
