### PR TITLE
[0.39] Cgroup v2 fixes backport

### PR DESCRIPTION
**Pull request by kolyshkin**
This is a backport of

* #2837
* #2839

to release-0.39 branch.

Fixes: https://github.com/google/cadvisor/issues/2878

### CODE REVIEW

**Comment by kolyshkin** [comment]
@googlebot I consent.

**Comment by giuseppe** [comment]
@googlebot I consent.

**Comment by giuseppe** [comment]
all green!

**Comment by kolyshkin** [comment]
@bobbypage PTAL

**Review by Creatone — APPROVED** [review]
LGTM

**Pull request merged**
