### PR TITLE
Provide PSR information for containers.

### PR DESCRIPTION
**Pull request by mJace**
Allow cadvisor to provide PSR information when doing `ps` to containers now.
PSR is a `ps` output option, it shows which cpu that current process runs on.

The related issue:
https://github.com/google/cadvisor/issues/2290

### CODE REVIEW

**Comment by mJace** [comment]
@googlebot I signed it!

**Comment by mJace** [comment]
@dashpole How do I run the test in my fork?
I tried to `make test` at /cadvisor when I just fork master and without changing any code but it has some failure.

**Comment by dashpole** [comment]
```
++ git diff --name-only pages
W0816 19:01:14.397] + [[ ! -z pages/static/assets.go ]]
W0816 19:01:14.398] + echo 'Found changes to UI assets:'
W0816 19:01:14.398] + git diff --name-only pages
W0816 19:01:14.405] ++ make assets FORCE=true
I0816 19:01:14.507] Found changes to UI assets:
I0816 19:01:14.508] pages/static/assets.go
I0816 19:01:15.332] Run: >> building assets
W0816 19:01:15.434] + echo 'Run: >> building assets'
W0816 19:01:15.434] + exit 1
```

Try just running `make` locally to reproduce the failure.

**Comment by mJace** [comment]
@dashpole  Sorry, I have some problem reproducing the `make` failure.

I have this error when running `make` in my master and numa_support branch
[log.txt](https://github.com/google/cadvisor/files/3518498/log.txt)
My master is same as latest google/cadvisor
d200c9f558b0a8051d728fd8bb74d0469c6a36e1

But if I manually copy 3 modified files to my local google/master and run `make`.
It can run successfully.
[logSuccess.txt](https://github.com/google/cadvisor/files/3518520/logSuccess.txt)

**Comment by dashpole** [comment]
ah, apologies.  I forgot about some changes we made to scripts a while back.
You will need to run `make assets FORCE=true`.

It looks like there is a bug with the script that actually runs `make assets FORCE=true`, rather than printing it: https://github.com/google/cadvisor/blob/master/build/prow_e2e.sh#L34

I opened #2296 to fix the print statement.

**Comment by mJace** [comment]
@dashpole 
Thanks for your fix.
Should I wait for the #2296 to merged to master and re-create this PR again?

Cuz, I still have trouble to run `make` at my own fork, even if I change the prow_e2e.sh as #2296 did.

But it seems like they are 2 different problems?
#2296 is for pull-cadvisor-e2e CI fail.
the `make` fail at my on fork is another story.

**Comment by dashpole** [comment]
Yeah, you are correct.  To fix the failure here, run `make assets FORCE=true` to rebuild UI assets, and commit the changes.

My PR just fixes the error message from https://github.com/google/cadvisor/pull/2291#issuecomment-522649848 so it tells you how to fix that problem.

**Comment by mJace** [comment]
> Yeah, you are correct. To fix the failure here, run `make assets FORCE=true` to rebuild UI assets, and commit the changes.
> 
> My PR just fixes the error message from [#2291 (comment)](https://github.com/google/cadvisor/pull/2291#issuecomment-522649848) so it tells you how to fix that problem.

I see, thank you.

**Comment by dashpole** [comment]
sorry, if you can rebase this, i'm happy to merge it.

**Comment by mJace** [comment]
@dashpole  Thank you!  
But I have a build error on the latest master branch 425e2117eb76752be0b34f6d20b2b8962283bb61  
```
make build
>> building assets
>> building binaries
>> building cadvisor
internal/storage/influxdb/influxdb.go:29:2: cannot find package "github.com/influxdb/influxdb/client" in any of:
	/usr/local/go/src/github.com/influxdb/influxdb/client (from $GOROOT)
	/home/jace/go/src/github.com/influxdb/influxdb/client (from $GOPATH)
make: *** [Makefile:70: build] Error 1
```  
Can you check this for me? I tried go v1.11 v1.12 v1.13  
maybe need to define the influxdb/client in go.mod?

**Comment by dashpole** [comment]
I would just rebase on master.  If it has problems, you can check the logs from the presubmits if you can't get it working in your dev env.  I think we use go 1.14 now btw

**Comment by mJace** [comment]
@dashpole  I rebased my branch. Could you take a look? thank you!

**Pull request merged**
