### PR TITLE
Stop leaking testing dependencies (and flags) in non-testing builds

### PR DESCRIPTION
**Pull request by timstclair**
Specifically, the "github.com/stretchr/testify/mock" pulls in "net/http/httptest" which adds the "httptest.serve" flag.

### CODE REVIEW

**Comment by pwittrock** [comment]
fyi test failure:

/var/lib/jenkins/workspace/project/src/github.com/google/cadvisor/container/factory_test.go:49: undefined: FactoryForMockContainerHandler

**Comment by timstclair** [comment]
I'm sorry, I could have sworn this worked the first time around... For the build tags to work, we would always need to specify `-tags test` when running unit tests, which is annoying. It looks like the go standard library just appends `_test` to test-only files (even if they don't contain any tests), so I'll go with that method unless there's any objections...

**Comment by timstclair** [comment]
Actually, I was wrong again - `*_test.go` files aren't exported, which is problematic for `container/mock.go` which is required by the `manager` package. So, I think the only option without a more substantial refactoring (to move test utilities to their own package) is to use the test tag. WDYT?

**Comment by timstclair** [comment]
PTAL

/cc @jimmidyson @vishh

**Comment by vishh** [comment]
Can we move the mock/stubs to a separate package?

**Comment by vishh** [comment]
This change is fine by me, although less ideal.

**Comment by timstclair** [comment]
> Can we move the mock/stubs to a separate package?

It's not that simple unfortunately... just moving the file to a separate package creates a circular dependency. The circular dependency could be fixed by moving tests to a _test package, but then they lose access to the unexported types. The types could be exported in another _test.go file, but in the end I think the build tags are cleaner... WDYT?

**Comment by vishh** [comment]
Got it. I'm fine with this change. It does not affect regular workflow unless we use `go` tools directly.

**Comment by pwittrock** [comment]
yay more credential failures

**Comment by pwittrock** [comment]
@k8s-bot test this please

**Comment by pwittrock** [comment]
I am good with this as long as the tests pass

**Comment by vishh** [comment]
Build is still failing. I suspect this is because the jenkins has not been updated to use `make` yet. I will make that change now.

**Comment by timstclair** [comment]
> Build is still failing. I suspect this is because the jenkins has not been updated to use make yet. I will make that change now.

Where do you see that? I just see the auth failure...

**Comment by pwittrock** [comment]
#1108 Should make these auth failures go away

**Comment by pwittrock** [comment]
@k8s-bot please test this

**Comment by pwittrock** [comment]
@k8s-bot test this please

**Comment by pwittrock** [comment]
LGTM.  Ok to self merge

**Pull request merged**
