### PR TITLE
Docker based integration test for cadvisor

### PR DESCRIPTION
**Pull request by dims**
- Add a docker based test that works on ubuntu and macOS
- Run the new make target using github actions

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
@dashpole 3 failures remain:
- TestDockerContainerNetworkStats : is a flake sometimes it works, sometimes it doesn't and works better if i bump the wait time
- TestDockerFilesystemStats : `vfs` support is busted?
- TestMachineInformationIsReturned : this is a regression for DIND scenarios, we don't have `/sys/devices/system/node/` directory at all, the change was introduced [recently](https://github.com/google/cadvisor/commit/c5a9232a94846cdd9f2a80b3a969a7717e880e10#diff-665621117cfccff84f309898d5d27bfbR47), looks like we stopped parsing contents of `/proc/cpuinfo`

```
>> starting cAdvisor locally
Waiting for cAdvisor to start ...
>> running integration tests against local cAdvisor
I0325 14:53:17.421730     659 framework.go:332] About to run - [sudo docker run -d kubernetes/pause]
I0325 14:53:19.235472     659 framework.go:332] About to run - [sudo docker rm -f 22d5597787a466111b9dcdfc8153c0664734c949d25c10eb86e80f0c0be3c101]
I0325 14:53:19.463528     659 framework.go:332] About to run - [sudo docker run -d --name test-docker-container-by-name-659 kubernetes/pause]
I0325 14:53:19.825571     659 framework.go:332] About to run - [sudo docker rm -f a30376ef8bb88c0349f11f91f9cb4292067e70e001b255500a3b0e5cfae989b8]
I0325 14:53:20.078523     659 framework.go:332] About to run - [sudo docker run -d kubernetes/pause]
I0325 14:53:20.424429     659 framework.go:332] About to run - [sudo docker run -d kubernetes/pause]
I0325 14:53:20.792645     659 framework.go:332] About to run - [sudo docker rm -f 42291205d00e2d92839956a9d3d80a3114d63eea478acd3192cee5c8f5d9c3e2]
I0325 14:53:21.028348     659 framework.go:332] About to run - [sudo docker rm -f 01c5057828dad221548d8e8e9ee6a440938a81cada860ad4baf934d22406c941]
I0325 14:53:21.268462     659 framework.go:332] About to run - [sudo docker run -d --name test-basic-docker-container-659 kubernetes/pause]
I0325 14:53:21.629014     659 framework.go:332] About to run - [sudo docker rm -f 33503fb2cefb23055aa43aff58783e7955bf48a7651d31fdb6528a49e6677acd]
I0325 14:53:21.861393     659 framework.go:332] About to run - [sudo docker run -d --cpu-shares 2048 --cpuset-cpus 0 --memory 1073741824 --env TEST_VAR=FOO --label bar=baz kubernetes/pause]
I0325 14:53:22.209161     659 framework.go:332] About to run - [sudo docker rm -f f25f871a38c81d286a4b8746a644b0a10e17815c178d82f5ecc3c5689ccf6e71]
I0325 14:53:22.449851     659 framework.go:332] About to run - [sudo docker run -d busybox ping www.google.com]
I0325 14:53:23.983438     659 framework.go:332] About to run - [sudo docker rm -f ea0d422e0c171a640c29981d23511abf9c5381c3c4c2f862455e2f96f12256ca]
I0325 14:53:24.237448     659 framework.go:332] About to run - [sudo docker run -d busybox ping www.google.com]
I0325 14:53:24.601501     659 framework.go:332] About to run - [sudo docker rm -f 98cd9b7f6b4f332b835e6c9d0f38ea64ba65706ddc65de6d39b0f112a42733d4]
I0325 14:53:24.820862     659 framework.go:332] About to run - [sudo docker run -d busybox watch -n.1 wget http://www.google.com/]
I0325 14:53:35.198030     659 framework.go:332] About to run - [sudo docker rm -f bb88b9f2f36778dcfce16ef3f5e51e8d4d5729b34481014853bb9a187a1aac56]
--- FAIL: TestDockerContainerNetworkStats (10.65s)
    docker_test.go:298:
        	Error Trace:	docker_test.go:298
        	Error:      	Should not be: 0x0
        	Test:       	TestDockerContainerNetworkStats
        	Messages:   	Network tx and rx bytes should not be equal
    docker_test.go:299:
        	Error Trace:	docker_test.go:299
        	Error:      	Should not be: 0x0
        	Test:       	TestDockerContainerNetworkStats
        	Messages:   	Network tx and rx packets should not be equal
I0325 14:53:35.474737     659 framework.go:332] About to run - [sudo docker info]
I0325 14:53:35.579240     659 framework.go:332] About to run - [sudo docker run -d busybox /bin/sh -c dd if=/dev/zero of=/file count=2 bs=8 & ping google.com]
I0325 14:53:35.975774     659 framework.go:332] About to run - [sudo docker rm -f d22535882a390f809baad20203c3b971a1fabd2dfbab9f0b633019b963414996]
--- FAIL: TestDockerFilesystemStats (0.75s)
    docker_test.go:356:
        	Error Trace:	docker_test.go:356
        	Error:      	Expected value not to be nil.
        	Test:       	TestDockerFilesystemStats
        	Messages:   	got info: {Spec:{CreationTime:2020-03-25 14:53:35.6285766 +0000 UTC Aliases:[sharp_mclean d22535882a390f809baad20203c3b971a1fabd2dfbab9f0b633019b963414996] Namespace:docker Labels:map[] Envs:map[] HasCpu:true Cpu:{Limit:1024 MaxLimit:0 Mask:0-5 Quota:0 Period:0} HasMemory:true Memory:{Limit:9223372036854771712 Reservation:9223372036854771712 SwapLimit:9223372036854771712} HasHugetlb:true HasCustomMetrics:false CustomMetrics:[] HasProcesses:true Processes:{Limit:0} HasNetwork:true HasFilesystem:true HasDiskIo:true Image:busybox} Stats:[0xc00017c300]}
--- FAIL: TestMachineInformationIsReturned (0.00s)
    machine_test.go:34: Machine info has unexpected number of cores: 0
    machine_test.go:52: Inodes not available for device "devpts"
FAIL
>> stopping cAdvisor
+ EXIT_VALUE=1
+ set +o xtrace
Cleaning up after docker in docker.
================================================================================
Cleaning up binfmt_misc ...
================================================================================
Done cleaning up after docker in docker.
make: *** [docker-test-integration] Error 1
```

**Comment by dashpole** [comment]
> TestMachineInformationIsReturned : this is a regression for DIND scenarios, we don't have /sys/devices/system/node/ directory at all, the change was introduced recently, looks like we stopped parsing contents of /proc/cpuinfo

That is concerning.  There were some builds (arm) that don't have /proc/cpuinfo, and fell back to /sys/devices/system/node in the old model.  I was hoping that by moving to /sys/ for everything, we could make it work for all users, but...

I'm surprised /proc files exist inside the container...

/cc @katarzyna-z

**Comment by dims** [comment]
@dashpole i concentrated on just linux for now ... made great progress. In fact we can just run all the stuff we need in github actions itself including the integration tests:
https://github.com/dims/cadvisor/runs/538381384

**Comment by dims** [comment]
looks like with a little bit of tweaking we can support arm64 based testing as well (and `macos-latest` too!)

**Comment by dims** [comment]
@dashpole please see a run of the tests here https://github.com/dims/cadvisor/runs/566103922

**Comment by dims** [comment]
@dashpole also see https://github.com/kubernetes/test-infra/issues/12863

**Comment by iwankgb** [comment]
@dims @dashpole it would be great to have it merged - I'm just going to start working on integration tests for perf.

**Comment by dashpole** [comment]
Thanks for all of the flake fixes along with this!  That network one has been around a long time...

**Pull request merged**
