### PR TITLE
Add inodes to /metrics endpoint

### LINKED ISSUE #1413: Expose inodes and inodes_free in /metrics endpoint
I'm using cadvisor with Prometheus for node monitoring and I'd really like to see the `inodes` and `inodes_free` stats in the `/metrics` endpoint. I'm having an issue where my inodes are being consumed but I still have available disk space, and I'd like to watch that before I get a "no space left on device" error.

### PR DESCRIPTION
**Pull request by micahhausler**
Closes #1413

### CODE REVIEW

**Comment by micahhausler** [comment]
Can someone "ok to test" this?

**Comment by timstclair** [comment]
ok to test

**Comment by timstclair** [comment]
Could you set a non-zero-valued inodes free/total in the test container info?

**Comment by micahhausler** [comment]
@timothysc Updated

**Comment by micahhausler** [comment]
@timothysc I think that the test container can't get the inodes of the device. Do you want me to do a check for `if fs.HasInodes {}` or just zero-out the test data?

**Comment by timstclair** [comment]
I think you just need to manually add the values here: https://github.com/google/cadvisor/blob/master/metrics/prometheus_test.go#L130

**Comment by timstclair** [comment]
LGTM

**Pull request merged**
