### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by waleedsamy**
fix broken link to influxdb.md

### CODE REVIEW

**Comment by waleedsamy** [comment]
I signed it!

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
@waleedsamy needs a rebase

**Comment by timstclair** [comment]
Sorry, this needs another rebase. I will merge it as soon as you do.

**Comment by waleedsamy** [comment]
@thomaso-mirodin @vishh I rebased it again.

**Pull request merged**
