### PR TITLE
test!

### PR DESCRIPTION
**Pull request by dashpole**
weeeeeeeeeeeee

### CODE REVIEW

**Comment by dashpole** [comment]
cc @BenTheElder

**Comment by BenTheElder** [comment]
should test here for fixed log uploads after https://github.com/kubernetes/test-infra/pull/6625

**Comment by BenTheElder** [comment]
It works! https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/google_cadvisor/1880/pull-cadvisor-e2e/632/

**Comment by dashpole** [comment]
look at those gorgeous logs...

**Pull request closed without merging**
