### PR TITLE
container: crio: change crio socket

### PR DESCRIPTION
**Pull request by runcom**
@mrunalp @smarterclayton @derekwaynecarr PTAL

ref https://github.com/kubernetes-incubator/cri-o/pull/1030

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
to support a smooth transition, can we check for one, and then the other?

**Comment by dashpole** [comment]
@derekwaynecarr should this be cherrypicked to the kubernetes 1.8.2 release along with #1770?

**Comment by dashpole** [comment]
FYI, I plan to cut cadvisor v0.28.1, which will correspond to k8s v1.9.0 this Friday, 11/17.

**Comment by derekwaynecarr** [comment]
@dashpole -- this can correspond to 1.9, @runcom - can you confirm the 1.9 cri-o packaging is in the new location?

**Comment by runcom** [comment]
> can you confirm the 1.9 cri-o packaging is in the new location?

yeah, the plan is to move to `/var/run/crio/crio.sock` for 1.9 (we're at 1.8 still)

**Comment by runcom** [comment]
CRI-O PR is here now https://github.com/kubernetes-incubator/cri-o/pull/1154

**Comment by derekwaynecarr** [comment]
@dashpole -- this should only go in kube 1.9 tracking releases and not kube 1.8 prior streams.

**Pull request merged**
