### PR TITLE
Add watcher for zfs similar to devicemapper

### PR DESCRIPTION
**Pull request by bakins**
After testing, this seems to give the most consistent view of ZFS compared to the other providers. It is a bit more code than I would like, but it is modeled after the devicemapper code.

### CODE REVIEW

**Comment by l8nite** [comment]
Would be nice to see some movement on this one.

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by dashpole** [comment]
Apologies for being slow.  The code changes look good, but dont have the context to review this.  @derekwaynecarr, if you could give this a quick look, that would be appreciated.

**Comment by dashpole** [comment]
@bakins, this will eventually need to be squashed and rebased.

**Comment by bakins** [comment]
@dashpole I'll rebase and squash. Happy to answer any questions, as well.  This is based on the devicemapper code in cadvisor but does zfs rather than thin_ls to get disk/filesystem stats.

**Comment by dashpole** [comment]
I've read up on Devicemapper and ZFS, and I think I mostly understand this PR.
How does this differ from the current behavior for ZFS?  Do we currently not support it at all?  Or does it just not work?

**Comment by bakins** [comment]
Squashed.  

BTW - we've been running this for a while by patching Kubernetes.

**Pull request merged**
