### PR TITLE
Corrected Typo in Clusterrole & Clusterrolebinding

### PR DESCRIPTION
**Pull request by kimminger**
- corrected filenames
- update kustomization file

### CODE REVIEW

**Comment by dashpole** [comment]
I can merge this as soon as the CLA is complete.

**Comment by dashpole** [comment]
ah, apologies.  Presubmits were broken after the go version update.  I just merged the fix: https://github.com/google/cadvisor/pull/2339.  You will have to rebase on top of that for presubmits to pass.

**Comment by kimminger** [comment]
@googlebot I signed it!

**Comment by kimminger** [comment]
Thanks @dashpole for reviewing
I need to close this PR, since i made a mistake pushing bloated commit history with wrong mail-address.
So i cleaned up the mess in
https://github.com/google/cadvisor/pull/2343

Sorry for the inconvenience

**Pull request closed without merging**
