### PR TITLE
Add mapped_file metric

### PR DESCRIPTION
**Pull request by stevenjm**
This is a simple fix for https://github.com/google/cadvisor/issues/2016.

### CODE REVIEW

**Comment by stevenjm** [comment]
I signed it!

**Comment by gwkunze** [comment]
I signed it!

**Comment by stevenjm** [comment]
cla update

**Comment by stevenjm** [comment]
@dashpole Both the committer and the PR author are covered by the same signed corporate CLA, but the automation doesn't seem to be recognising that. Is there anything left for us to do?

**Comment by dashpole** [comment]
I can check to see if the corporate CLA has been processed.  Can you ping me the name of the corporation on slack (username is dashpole), or email it to me?

**Comment by stevenjm** [comment]
Closing this so the commit author can open one and hopefully get the CLA check to pass.

**Comment by stevenjm** [comment]
Replacement PR: https://github.com/google/cadvisor/pull/2034

**Pull request closed without merging**
