### PR TITLE
Add the support for redis in cAdvisor's storage

### PR DESCRIPTION
**Pull request by superzhaoyy**
provide redis driver for cAdvisor's storage

### CODE REVIEW

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
One thing I noticed, is this just always over-writing the same key? Such that we only store one value? I'm not as familiar with Redis so I apologize for the noob question :)

**Comment by superzhaoyy** [comment]
hi@vmarmol .
you can pass some additional flags to cAdvisor telling it what's the key when you run a cAdvisor.
when a cAdvisor is running ,the key is unique,we use a list to store the value.
At set intervals, we add the newest values to the list every time .you can use redis's "LRANGE" to get any range of the list. It'sflexible.

for example：
redis> LRANGE cadvisor 0 10      // we can get ten of the latest data

**Comment by vmarmol** [comment]
Thanks for explaining @superzhaoyy!

LGTM, merging.

**Pull request merged**
