### PR TITLE
Release v0.23.4 for kubernetes 1.3

### PR DESCRIPTION
**Pull request by dchen1107**
Cherry-pick release:
  - Check for thin_is binary in path for devicemapper when using ThinPoolWatcher
  - Fix uint64 overflow issue for CPU stats

cc/ @kubernetes/sig-node @Random-Liu

### CODE REVIEW

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/27573

**Comment by dchen1107** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
LGTM

**Comment by pwittrock** [comment]
LGTM

**Pull request merged**
