### PR TITLE
Allow {memory, cpuLoad, and perf_event} metrics to be disabled

### PR DESCRIPTION
**Pull request by bnutt**
Adds ability to disable {memory, cpuLoad, and perf_event} metrics via --disable_metrics flag.

### CODE REVIEW

**Comment by bnutt** [comment]
@googlebot I signed it!

**Review by Creatone — APPROVED** [review]
LGTM

**Comment by eero-t** [comment]
Btw. Here's a change that allows disabling all metrics in AllMetrics list: https://github.com/eero-t/cadvisor/commit/58e2d16326634cd3b18750131463d91168717126

**Pull request merged**
