### PR TITLE
Modify GetTopology to read information only from sysfs

### PR DESCRIPTION
**Pull request by katarzyna-z**
* Move sysfs related functions needed to get nodes' information and tests into utils/sysfs
* Add tests for sysfs related functions

Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>

Summary of changes:
- Modified `GetTopology` to read information in more generic way, reading information only form sysfs
- Modifed `GetTopology` to provide elegantly support for NUMA nodes without any CPU
- Moved sysfs related functions needed to get information about NUMA nodes and tests into "utils/sysfs" directory
- `GetHugePagesInfo` is copied from machine/machine.go into utils/sysinfo/sysinfo.go
- Added tests for sysfs related functions
- Removed `findNode`, `addNode`, `getNodeIdFromCpuBus` and `getCoreIdFromCpuBus` which are no longer needed

Notice: In the future the rest of sysfs related functions could be moved from machine/machine.go into utils/sysfs and utils/sysfsinfo but I don't want to make it in this quite big pull request.

### CODE REVIEW

**Comment by iwankgb** [comment]
For the record: part of #2388 it is.

**Comment by katarzyna-z** [comment]
I see that tests passed. @dashpole what do you think about changes introduced in this pull request?

**Comment by dashpole** [comment]
Sorry for the slow review.  I just had to find time to do it.

**Comment by katarzyna-z** [comment]
@dashpole I know that it was time demanding review so thank you very much for finding a time ❤️  I'm also happy that some parts of code are now cleaner.

**Pull request merged**
