### PR TITLE
Moved max_housekeeping and allow_dynamic_housekeeping flags to cadvisor.go

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by vmarmol** [comment]
We should make this change in the Kubernetes configuration rather than the default for cAdvisor I think.

**Comment by piosz** [comment]
The changed is required to change the value of max_housekeeping_interval in Kubernetes. PTAL

**Comment by vmarmol** [comment]
LGTM, thanks @piosz!

**Comment by vmarmol** [comment]
ok to test

**Comment by piosz** [comment]
Thanks for review!

**Pull request merged**
