### PR TITLE
Improve information about metrics

### PR DESCRIPTION
**Pull request by katarzyna-z**
- Corrected information about perf metrics
- Add information about build flags required for metrics

### CODE REVIEW

**Comment by dashpole** [comment]
Looks like the divider is missing between container_perf_events_total and container_perf_metric_scaling_ratio, and the divider above libpfm for container_perf_events_total.

**Comment by katarzyna-z** [comment]
I don't see that... I see 5 dividers in lines with `container_perf_events_total` and 5 dividers in line with `container_perf_metric_scaling_ratio`

**Comment by dashpole** [comment]
I only see it when displaying the rich diff... not actually sure why it happens.  We can fix it in a follow-up if needed.

**Comment by dashpole** [comment]
huh, I don't see the problem anymore in the actual page: https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md

**Pull request merged**
